# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .ci-keep

default:
  image:
    name: gitlab-master.nvidia.com:5005/toronto_dl_lab/ncore:dev
  tags:
    - type/docker
    - os/linux
    - arch/x86_64
  before_script:
    # Fix permission as we are running as a local user
    - git config --global --add safe.directory /builds/Toronto_DL_Lab/ncore
    - |
      if test -d $CI_PROJECT_DIR/.ci-keep; then
        sudo chown -R developer $CI_PROJECT_DIR/.ci-keep
      fi

    # Setup python-package / remote cache credentials
    - echo "machine $ARTIFACTORY_MACHINE" >> ~/.netrc
    - echo "  login $ARTIFACTORY_LOGIN" >> ~/.netrc
    - echo "  password $ARTIFACTORY_PASSWORD" >> ~/.netrc

    - echo "machine $PYPACKAGE_MACHINE" >> ~/.netrc
    - echo "  login $PYPACKAGE_LOGIN" >> ~/.netrc
    - echo "  password $PYPACKAGE_PASSWORD" >> ~/.netrc
   
    # Enable remote-cache
    - echo "build --remote_cache=$REMOTE_CACHE_URL" >> .bazelrc.user
    - echo "test  --remote_cache=$REMOTE_CACHE_URL" >> .bazelrc.user

    # Setup persistent local disk-cache
    - echo "build --disk_cache=$CI_PROJECT_DIR/.ci-keep/cache" >> .bazelrc.user
    - echo "test  --disk_cache=$CI_PROJECT_DIR/.ci-keep/cache" >> .bazelrc.user

    # Setup persistent output folder
    - echo ".ci-keep" >> .bazelignore
    - echo "startup --output_base $CI_PROJECT_DIR/.ci-keep/output" >> .bazelrc.user

build+test:
  stage: build
  script:
    - bazelisk version

    # Check format declarations are not missing
    - bazelisk run //:bzlformat_missing_pkgs_test

    # Build+test all remaining targets
    - bazelisk build ...
    - bazelisk test ...
  allow_failure: false

pages:
  stage: build
  script:
  - bazelisk version

  # Build the HTML documentation
  - bazelisk build //docs:ncore

  # Move it to the output artifact for upload (requires root right to write)
  - sudo mv bazel-bin/docs/ncore_html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
