# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

variables:
  GIT_CLEAN_FLAGS: -ffdx -e .ci-keep

default:
  image:
    name: gitlab-master.nvidia.com:5005/nrs/ncore:dev
  tags:
    - type/docker
    - os/linux
    - arch/x86_64
    - gpu
  before_script:
    # Fix permission as we are running as a local user
    - sudo chown -R developer /home/developer
    - git config --global --add safe.directory /builds/nrs/ncore
    - |
      if test -d $CI_PROJECT_DIR/.ci-keep; then
        sudo chown -R developer $CI_PROJECT_DIR/.ci-keep
      fi

    # Setup python-package / remote cache credentials
    - echo "machine $ARTIFACTORY_MACHINE" >> ~/.netrc
    - echo "  login $ARTIFACTORY_LOGIN" >> ~/.netrc
    - echo "  password $ARTIFACTORY_PASSWORD" >> ~/.netrc

    - echo "machine $PYPACKAGE_MACHINE" >> ~/.netrc
    - echo "  login $PYPACKAGE_LOGIN" >> ~/.netrc
    - echo "  password $PYPACKAGE_PASSWORD" >> ~/.netrc
   
    # Enable remote-cache
    - echo "build --remote_cache=$REMOTE_CACHE_URL" >> .bazelrc.user
    - echo "test  --remote_cache=$REMOTE_CACHE_URL" >> .bazelrc.user

    # Setup persistent local disk-cache
    - echo "build --disk_cache=$CI_PROJECT_DIR/.ci-keep/cache" >> .bazelrc.user
    - echo "test  --disk_cache=$CI_PROJECT_DIR/.ci-keep/cache" >> .bazelrc.user

    # Handle CI cache tag and remove / re-init cache if required
    - scripts/ci/cache_tag.sh $CI_PROJECT_DIR/.ci-keep v1

    # Make use of local mypy cache 
    - mkdir -p $CI_PROJECT_DIR/.ci-keep/.mypy_cache
    - echo "build --sandbox_writable_path=$CI_PROJECT_DIR/.ci-keep/.mypy_cache" >> .bazelrc.user
    - echo "build --action_env=MYPY_CACHE_DIR=$CI_PROJECT_DIR/.ci-keep/.mypy_cache" >> .bazelrc.user

    # Setup persistent output folder
    - echo ".ci-keep" >> .bazelignore
    - echo "startup --output_base $CI_PROJECT_DIR/.ci-keep/output" >> .bazelrc.user

build+test:
  stage: build
  script:
    - bazelisk version

    # Check format declarations are not missing
    - bazelisk run //:bzlformat_missing_pkgs_test

    # Check code format
    - bazelisk run //:format.check

    # Build+test all remaining targets
    - bazelisk build ...
    - bazelisk test ...
  allow_failure: false

pages:
  stage: deploy
  script:
  - bazelisk version

  # Build the HTML documentation
  - bazelisk clean
  - bazelisk build //docs:ncore

  # Move it to the output artifact for upload (requires root right to write)
  - sudo mv bazel-bin/docs/ncore_html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

wheel:
  stage: deploy
  script:
  - bazelisk version

  # Build the wheels
  - bazelisk clean
  - bazelisk build //ncore:ncore_wheel
  - bazelisk build //3rdparty/poisson_recon:poisson_recon_wheel

  # Try to deploy the wheels (skip if version already exists)
  - pip install twine
  - python -m twine upload --repository-url https://gitlab-master.nvidia.com/api/v4/projects/61004/packages/pypi bazel-bin/ncore/*.whl --verbose --skip-existing --non-interactive
  - python -m twine upload --repository-url https://gitlab-master.nvidia.com/api/v4/projects/61004/packages/pypi bazel-bin/3rdparty/poisson_recon/*.whl --verbose --skip-existing --non-interactive
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
