# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

import json

import h5py
import numpy as np

from pathlib import Path

class DataWriter():
    ''' DataWriter implementing format-specific serialization specifications to store data generated by data-converters '''

    INDEX_DIGITS = 6 # the number of integer digits to pad counters in output filenames to

    CAMERAS_BASE_DIR = 'cameras'
    LIDARS_BASE_DIR = 'lidars'
    RADARS_BASE_DIR = 'lidars'

    def __init__(self, sequence_output_dir: Path, camera_ids: list[str], lidar_ids: list[str], radar_ids: list[str]):
        ''' 
        Instantiate data writer and initialize the default folder structure for a given sequence and sensor IDs
        '''

        self.camera_ids = camera_ids
        self.lidar_ids = lidar_ids
        self.radar_ids = radar_ids

        self.sequence_output_dir = sequence_output_dir

        # Create output folder structure
        for camera_id in self.camera_ids:
            (self.sequence_output_dir / self.CAMERAS_BASE_DIR / camera_id).mkdir(parents=True, exist_ok=True)

        for lidar_id in self.lidar_ids:
            (self.sequence_output_dir / self.LIDARS_BASE_DIR / lidar_id).mkdir(parents=True, exist_ok=True)

        for radar_id in self.radar_ids:
            (self.sequence_output_dir / self.RADARS_BASE_DIR / radar_id).mkdir(parents=True, exist_ok=True)

    # Individual 'store*' methods performing data sanity checks and serialize consistent output formats
    def store_poses(self, T_rig_world_base: np.array, T_rig_worlds: np.array, T_rig_world_timestamps_ms: list[int]) -> None:
        # sanity / consistency checks
        assert T_rig_world_base.shape == (4, 4)
        assert T_rig_world_base.dtype == np.dtype('float64')
        assert T_rig_worlds.shape[0] == len(T_rig_world_timestamps_ms)
        assert T_rig_worlds.shape[1:3] == (4, 4)
        assert T_rig_worlds.dtype == np.dtype('float64')

        with h5py.File(self.sequence_output_dir / 'poses.hdf5', "w") as f:
            f.create_dataset('T_rig_world_base', data=T_rig_world_base)
            f.create_dataset('T_rig_worlds', data=T_rig_worlds)
            f.create_dataset('T_rig_world_timestamps_ms', data=T_rig_world_timestamps_ms)


    def store_labels(self, labels : dict, frame_labels: dict) -> None:
        output = {'labels': labels, 'frame_labels': frame_labels}

        # TODO: add sanity checks on the final label structure before output

        with open(self.sequence_output_dir / 'labels.json', "w") as outfile:
            outfile.write(json.dumps(output))


    def store_meta(self, version: str, calibration_type: str, egomotion_type: str) -> None:
        output = {'version': version, 'egomotion_type': egomotion_type, 'calibration_type': calibration_type}

        with open(self.sequence_output_dir / 'meta.json', "w") as outfile:
            outfile.write(json.dumps(output))
