# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/camera_calibration.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import math_pb2 as protos_dot_math__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/camera_calibration.proto',
  package='deepmap.api',
  syntax='proto3',
  serialized_options=_b('\n\016ai.deepmap.apiZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protos'),
  serialized_pb=_b('\n\x1fprotos/camera_calibration.proto\x12\x0b\x64\x65\x65pmap.api\x1a\x11protos/math.proto\"\xbb\x02\n\x19MonoCalibrationParameters\x12\x13\n\x0bimage_width\x18\x01 \x01(\x05\x12\x14\n\x0cimage_height\x18\x02 \x01(\x05\x12+\n\rcamera_matrix\x18\x03 \x01(\x0b\x32\x14.deepmap.api.MatrixD\x12\x35\n\x17\x64istortion_coefficients\x18\x04 \x01(\x0b\x32\x14.deepmap.api.MatrixD\x12\x32\n\x14rectification_matrix\x18\x05 \x01(\x0b\x32\x14.deepmap.api.MatrixD\x12/\n\x11projection_matrix\x18\x06 \x01(\x0b\x32\x14.deepmap.api.MatrixD\x12*\n\"rolling_shutter_delay_microseconds\x18\x07 \x01(\r\"\xd1\x01\n\x1bStereoCalibrationParameters\x12\x12\n\nsensor_ids\x18\x01 \x03(\r\x12/\n\x11rotation_matrices\x18\x03 \x03(\x0b\x32\x14.deepmap.api.MatrixD\x12\x32\n\x14translation_matrices\x18\x04 \x03(\x0b\x32\x14.deepmap.api.MatrixD\x12\x39\n\x1b\x64isparity_to_depth_matrices\x18\x05 \x03(\x0b\x32\x14.deepmap.api.MatrixDBP\n\x0e\x61i.deepmap.apiZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protosb\x06proto3')
  ,
  dependencies=[protos_dot_math__pb2.DESCRIPTOR,])




_MONOCALIBRATIONPARAMETERS = _descriptor.Descriptor(
  name='MonoCalibrationParameters',
  full_name='deepmap.api.MonoCalibrationParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_width', full_name='deepmap.api.MonoCalibrationParameters.image_width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_height', full_name='deepmap.api.MonoCalibrationParameters.image_height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_matrix', full_name='deepmap.api.MonoCalibrationParameters.camera_matrix', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='distortion_coefficients', full_name='deepmap.api.MonoCalibrationParameters.distortion_coefficients', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rectification_matrix', full_name='deepmap.api.MonoCalibrationParameters.rectification_matrix', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='projection_matrix', full_name='deepmap.api.MonoCalibrationParameters.projection_matrix', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rolling_shutter_delay_microseconds', full_name='deepmap.api.MonoCalibrationParameters.rolling_shutter_delay_microseconds', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=383,
)


_STEREOCALIBRATIONPARAMETERS = _descriptor.Descriptor(
  name='StereoCalibrationParameters',
  full_name='deepmap.api.StereoCalibrationParameters',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_ids', full_name='deepmap.api.StereoCalibrationParameters.sensor_ids', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rotation_matrices', full_name='deepmap.api.StereoCalibrationParameters.rotation_matrices', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation_matrices', full_name='deepmap.api.StereoCalibrationParameters.translation_matrices', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='disparity_to_depth_matrices', full_name='deepmap.api.StereoCalibrationParameters.disparity_to_depth_matrices', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=595,
)

_MONOCALIBRATIONPARAMETERS.fields_by_name['camera_matrix'].message_type = protos_dot_math__pb2._MATRIXD
_MONOCALIBRATIONPARAMETERS.fields_by_name['distortion_coefficients'].message_type = protos_dot_math__pb2._MATRIXD
_MONOCALIBRATIONPARAMETERS.fields_by_name['rectification_matrix'].message_type = protos_dot_math__pb2._MATRIXD
_MONOCALIBRATIONPARAMETERS.fields_by_name['projection_matrix'].message_type = protos_dot_math__pb2._MATRIXD
_STEREOCALIBRATIONPARAMETERS.fields_by_name['rotation_matrices'].message_type = protos_dot_math__pb2._MATRIXD
_STEREOCALIBRATIONPARAMETERS.fields_by_name['translation_matrices'].message_type = protos_dot_math__pb2._MATRIXD
_STEREOCALIBRATIONPARAMETERS.fields_by_name['disparity_to_depth_matrices'].message_type = protos_dot_math__pb2._MATRIXD
DESCRIPTOR.message_types_by_name['MonoCalibrationParameters'] = _MONOCALIBRATIONPARAMETERS
DESCRIPTOR.message_types_by_name['StereoCalibrationParameters'] = _STEREOCALIBRATIONPARAMETERS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MonoCalibrationParameters = _reflection.GeneratedProtocolMessageType('MonoCalibrationParameters', (_message.Message,), dict(
  DESCRIPTOR = _MONOCALIBRATIONPARAMETERS,
  __module__ = 'protos.camera_calibration_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.MonoCalibrationParameters)
  ))
_sym_db.RegisterMessage(MonoCalibrationParameters)

StereoCalibrationParameters = _reflection.GeneratedProtocolMessageType('StereoCalibrationParameters', (_message.Message,), dict(
  DESCRIPTOR = _STEREOCALIBRATIONPARAMETERS,
  __module__ = 'protos.camera_calibration_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.StereoCalibrationParameters)
  ))
_sym_db.RegisterMessage(StereoCalibrationParameters)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
