# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/coordinate_systems.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/coordinate_systems.proto',
  package='deepmap.api',
  syntax='proto3',
  serialized_options=_b('\n\016ai.deepmap.apiZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protos'),
  serialized_pb=_b('\n\x1fprotos/coordinate_systems.proto\x12\x0b\x64\x65\x65pmap.api*n\n\x10\x43oordinateSystem\x12\x1d\n\x19\x43OORDINATE_SYSTEM_UNKNOWN\x10\x00\x12\x0f\n\x0bLAT_LNG_ALT\x10\x01\x12\x15\n\x11VEHICLE_CARTESIAN\x10\x03\x12\x13\n\x0fLIDAR_CARTESIAN\x10\x04\x42P\n\x0e\x61i.deepmap.apiZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protosb\x06proto3')
)

_COORDINATESYSTEM = _descriptor.EnumDescriptor(
  name='CoordinateSystem',
  full_name='deepmap.api.CoordinateSystem',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COORDINATE_SYSTEM_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAT_LNG_ALT', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_CARTESIAN', index=2, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LIDAR_CARTESIAN', index=3, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=48,
  serialized_end=158,
)
_sym_db.RegisterEnumDescriptor(_COORDINATESYSTEM)

CoordinateSystem = enum_type_wrapper.EnumTypeWrapper(_COORDINATESYSTEM)
COORDINATE_SYSTEM_UNKNOWN = 0
LAT_LNG_ALT = 1
VEHICLE_CARTESIAN = 3
LIDAR_CARTESIAN = 4


DESCRIPTOR.enum_types_by_name['CoordinateSystem'] = _COORDINATESYSTEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
