# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/lat_lng_alt.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/lat_lng_alt.proto',
  package='deepmap.api',
  syntax='proto3',
  serialized_options=_b('\n\016ai.deepmap.apiB\016LatLngAltProtoZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protos'),
  serialized_pb=_b('\n\x18protos/lat_lng_alt.proto\x12\x0b\x64\x65\x65pmap.api\"Y\n\tLatLngAlt\x12\x18\n\x10latitude_degrees\x18\x01 \x01(\x01\x12\x19\n\x11longitude_degrees\x18\x02 \x01(\x01\x12\x17\n\x0f\x61ltitude_meters\x18\x03 \x01(\x02\"p\n\x0cLatLngAltBox\x12/\n\x0fmin_lat_lng_alt\x18\x01 \x01(\x0b\x32\x16.deepmap.api.LatLngAlt\x12/\n\x0fmax_lat_lng_alt\x18\x02 \x01(\x0b\x32\x16.deepmap.api.LatLngAlt\"=\n\x06LatLng\x12\x18\n\x10latitude_degrees\x18\x01 \x01(\x01\x12\x19\n\x11longitude_degrees\x18\x02 \x01(\x01\"_\n\tLatLngBox\x12(\n\x0bmin_lat_lng\x18\x01 \x01(\x0b\x32\x13.deepmap.api.LatLng\x12(\n\x0bmax_lat_lng\x18\x02 \x01(\x0b\x32\x13.deepmap.api.LatLngB`\n\x0e\x61i.deepmap.apiB\x0eLatLngAltProtoZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protosb\x06proto3')
)




_LATLNGALT = _descriptor.Descriptor(
  name='LatLngAlt',
  full_name='deepmap.api.LatLngAlt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude_degrees', full_name='deepmap.api.LatLngAlt.latitude_degrees', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude_degrees', full_name='deepmap.api.LatLngAlt.longitude_degrees', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='altitude_meters', full_name='deepmap.api.LatLngAlt.altitude_meters', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=130,
)


_LATLNGALTBOX = _descriptor.Descriptor(
  name='LatLngAltBox',
  full_name='deepmap.api.LatLngAltBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_lat_lng_alt', full_name='deepmap.api.LatLngAltBox.min_lat_lng_alt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_lat_lng_alt', full_name='deepmap.api.LatLngAltBox.max_lat_lng_alt', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=244,
)


_LATLNG = _descriptor.Descriptor(
  name='LatLng',
  full_name='deepmap.api.LatLng',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='latitude_degrees', full_name='deepmap.api.LatLng.latitude_degrees', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='longitude_degrees', full_name='deepmap.api.LatLng.longitude_degrees', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=307,
)


_LATLNGBOX = _descriptor.Descriptor(
  name='LatLngBox',
  full_name='deepmap.api.LatLngBox',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_lat_lng', full_name='deepmap.api.LatLngBox.min_lat_lng', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='max_lat_lng', full_name='deepmap.api.LatLngBox.max_lat_lng', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=404,
)

_LATLNGALTBOX.fields_by_name['min_lat_lng_alt'].message_type = _LATLNGALT
_LATLNGALTBOX.fields_by_name['max_lat_lng_alt'].message_type = _LATLNGALT
_LATLNGBOX.fields_by_name['min_lat_lng'].message_type = _LATLNG
_LATLNGBOX.fields_by_name['max_lat_lng'].message_type = _LATLNG
DESCRIPTOR.message_types_by_name['LatLngAlt'] = _LATLNGALT
DESCRIPTOR.message_types_by_name['LatLngAltBox'] = _LATLNGALTBOX
DESCRIPTOR.message_types_by_name['LatLng'] = _LATLNG
DESCRIPTOR.message_types_by_name['LatLngBox'] = _LATLNGBOX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LatLngAlt = _reflection.GeneratedProtocolMessageType('LatLngAlt', (_message.Message,), dict(
  DESCRIPTOR = _LATLNGALT,
  __module__ = 'protos.lat_lng_alt_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.LatLngAlt)
  ))
_sym_db.RegisterMessage(LatLngAlt)

LatLngAltBox = _reflection.GeneratedProtocolMessageType('LatLngAltBox', (_message.Message,), dict(
  DESCRIPTOR = _LATLNGALTBOX,
  __module__ = 'protos.lat_lng_alt_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.LatLngAltBox)
  ))
_sym_db.RegisterMessage(LatLngAltBox)

LatLng = _reflection.GeneratedProtocolMessageType('LatLng', (_message.Message,), dict(
  DESCRIPTOR = _LATLNG,
  __module__ = 'protos.lat_lng_alt_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.LatLng)
  ))
_sym_db.RegisterMessage(LatLng)

LatLngBox = _reflection.GeneratedProtocolMessageType('LatLngBox', (_message.Message,), dict(
  DESCRIPTOR = _LATLNGBOX,
  __module__ = 'protos.lat_lng_alt_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.LatLngBox)
  ))
_sym_db.RegisterMessage(LatLngBox)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
