# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/math.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/math.proto',
  package='deepmap.api',
  syntax='proto3',
  serialized_options=_b('\n\016ai.deepmap.apiZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protos'),
  serialized_pb=_b('\n\x11protos/math.proto\x12\x0b\x64\x65\x65pmap.api\"@\n\x07MatrixD\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x12\x11\n\trow_count\x18\x02 \x01(\r\x12\x14\n\x0c\x63olumn_count\x18\x03 \x01(\r\"+\n\x08Vector3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"G\n\x10SymmetricMatrixF\x12%\n\x1dupper_triangle_row_major_data\x18\x01 \x03(\x02\x12\x0c\n\x04size\x18\x02 \x01(\rBP\n\x0e\x61i.deepmap.apiZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protosb\x06proto3')
)




_MATRIXD = _descriptor.Descriptor(
  name='MatrixD',
  full_name='deepmap.api.MatrixD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='deepmap.api.MatrixD.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_count', full_name='deepmap.api.MatrixD.row_count', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='column_count', full_name='deepmap.api.MatrixD.column_count', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=98,
)


_VECTOR3D = _descriptor.Descriptor(
  name='Vector3D',
  full_name='deepmap.api.Vector3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='deepmap.api.Vector3D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='deepmap.api.Vector3D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='deepmap.api.Vector3D.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=100,
  serialized_end=143,
)


_SYMMETRICMATRIXF = _descriptor.Descriptor(
  name='SymmetricMatrixF',
  full_name='deepmap.api.SymmetricMatrixF',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='upper_triangle_row_major_data', full_name='deepmap.api.SymmetricMatrixF.upper_triangle_row_major_data', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='size', full_name='deepmap.api.SymmetricMatrixF.size', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['MatrixD'] = _MATRIXD
DESCRIPTOR.message_types_by_name['Vector3D'] = _VECTOR3D
DESCRIPTOR.message_types_by_name['SymmetricMatrixF'] = _SYMMETRICMATRIXF
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MatrixD = _reflection.GeneratedProtocolMessageType('MatrixD', (_message.Message,), dict(
  DESCRIPTOR = _MATRIXD,
  __module__ = 'protos.math_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.MatrixD)
  ))
_sym_db.RegisterMessage(MatrixD)

Vector3D = _reflection.GeneratedProtocolMessageType('Vector3D', (_message.Message,), dict(
  DESCRIPTOR = _VECTOR3D,
  __module__ = 'protos.math_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.Vector3D)
  ))
_sym_db.RegisterMessage(Vector3D)

SymmetricMatrixF = _reflection.GeneratedProtocolMessageType('SymmetricMatrixF', (_message.Message,), dict(
  DESCRIPTOR = _SYMMETRICMATRIXF,
  __module__ = 'protos.math_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.SymmetricMatrixF)
  ))
_sym_db.RegisterMessage(SymmetricMatrixF)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
