# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/track_data.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import transform_pb2 as protos_dot_transform__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/track_data.proto',
  package='alignment.data_wrapper',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x17protos/track_data.proto\x12\x16\x61lignment.data_wrapper\x1a\x16protos/transform.proto\"q\n\tUnwinding\x12\x30\n\ttransform\x18\x01 \x01(\x0b\x32\x1d.deepmap.api.RigidTransform3d\x12\x19\n\x11start_nanoseconds\x18\x02 \x01(\x04\x12\x17\n\x0f\x65nd_nanoseconds\x18\x03 \x01(\x04\"\xfd\x01\n\x0cSensorRecord\x12\x1e\n\x16timestamp_microseconds\x18\x01 \x01(\x04\x12\x37\n\x0b\x64\x61ta_format\x18\x02 \x01(\x0e\x32\".alignment.data_wrapper.DataFormat\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12$\n\x04pose\x18\x04 \x01(\x0b\x32\x16.deepmap.api.WorldPose\x12\x34\n\tunwinding\x18\x05 \x01(\x0b\x32!.alignment.data_wrapper.Unwinding\x12%\n\x1d\x64ynamic_points_mask_file_path\x18\x06 \x01(\t\"\xb2\x01\n\x0cLidarRecords\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\x05\x12\x35\n\x07records\x18\x03 \x03(\x0b\x32$.alignment.data_wrapper.SensorRecord\x12\'\n\x1flidar_to_vehicle_transform_path\x18\x04 \x01(\t\x12\x1a\n\x12unwind_point_cloud\x18\x05 \x01(\x08\"\xc2\x01\n\rCameraRecords\x12\x13\n\x0bsensor_name\x18\x01 \x01(\t\x12\x11\n\tsensor_id\x18\x02 \x01(\x05\x12\x35\n\x07records\x18\x03 \x03(\x0b\x32$.alignment.data_wrapper.SensorRecord\x12(\n camera_to_vehicle_transform_path\x18\x04 \x01(\t\x12(\n mono_calibration_parameters_path\x18\x05 \x01(\t\"\x91\x01\n\x13\x41lignedTrackRecords\x12=\n\x0e\x63\x61mera_records\x18\x01 \x03(\x0b\x32%.alignment.data_wrapper.CameraRecords\x12;\n\rlidar_records\x18\x02 \x03(\x0b\x32$.alignment.data_wrapper.LidarRecords*Y\n\nDataFormat\x12\x12\n\x0e\x46ORMAT_UNKNOWN\x10\x00\x12\x08\n\x04JPEG\x10\x01\x12\x07\n\x03PNG\x10\x02\x12\x1b\n\x17UNCOMPRESSED_POINTCLOUD\x10\x03\x12\x07\n\x03PLY\x10\x04\x62\x06proto3')
  ,
  dependencies=[protos_dot_transform__pb2.DESCRIPTOR,])

_DATAFORMAT = _descriptor.EnumDescriptor(
  name='DataFormat',
  full_name='alignment.data_wrapper.DataFormat',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORMAT_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='JPEG', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PNG', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNCOMPRESSED_POINTCLOUD', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLY', index=4, number=4,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=972,
  serialized_end=1061,
)
_sym_db.RegisterEnumDescriptor(_DATAFORMAT)

DataFormat = enum_type_wrapper.EnumTypeWrapper(_DATAFORMAT)
FORMAT_UNKNOWN = 0
JPEG = 1
PNG = 2
UNCOMPRESSED_POINTCLOUD = 3
PLY = 4



_UNWINDING = _descriptor.Descriptor(
  name='Unwinding',
  full_name='alignment.data_wrapper.Unwinding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='transform', full_name='alignment.data_wrapper.Unwinding.transform', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start_nanoseconds', full_name='alignment.data_wrapper.Unwinding.start_nanoseconds', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end_nanoseconds', full_name='alignment.data_wrapper.Unwinding.end_nanoseconds', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=188,
)


_SENSORRECORD = _descriptor.Descriptor(
  name='SensorRecord',
  full_name='alignment.data_wrapper.SensorRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp_microseconds', full_name='alignment.data_wrapper.SensorRecord.timestamp_microseconds', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_format', full_name='alignment.data_wrapper.SensorRecord.data_format', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='alignment.data_wrapper.SensorRecord.file_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pose', full_name='alignment.data_wrapper.SensorRecord.pose', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unwinding', full_name='alignment.data_wrapper.SensorRecord.unwinding', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dynamic_points_mask_file_path', full_name='alignment.data_wrapper.SensorRecord.dynamic_points_mask_file_path', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=444,
)


_LIDARRECORDS = _descriptor.Descriptor(
  name='LidarRecords',
  full_name='alignment.data_wrapper.LidarRecords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_name', full_name='alignment.data_wrapper.LidarRecords.sensor_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='alignment.data_wrapper.LidarRecords.sensor_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='records', full_name='alignment.data_wrapper.LidarRecords.records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lidar_to_vehicle_transform_path', full_name='alignment.data_wrapper.LidarRecords.lidar_to_vehicle_transform_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='unwind_point_cloud', full_name='alignment.data_wrapper.LidarRecords.unwind_point_cloud', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=447,
  serialized_end=625,
)


_CAMERARECORDS = _descriptor.Descriptor(
  name='CameraRecords',
  full_name='alignment.data_wrapper.CameraRecords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_name', full_name='alignment.data_wrapper.CameraRecords.sensor_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='alignment.data_wrapper.CameraRecords.sensor_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='records', full_name='alignment.data_wrapper.CameraRecords.records', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='camera_to_vehicle_transform_path', full_name='alignment.data_wrapper.CameraRecords.camera_to_vehicle_transform_path', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='mono_calibration_parameters_path', full_name='alignment.data_wrapper.CameraRecords.mono_calibration_parameters_path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=628,
  serialized_end=822,
)


_ALIGNEDTRACKRECORDS = _descriptor.Descriptor(
  name='AlignedTrackRecords',
  full_name='alignment.data_wrapper.AlignedTrackRecords',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='camera_records', full_name='alignment.data_wrapper.AlignedTrackRecords.camera_records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='lidar_records', full_name='alignment.data_wrapper.AlignedTrackRecords.lidar_records', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=825,
  serialized_end=970,
)

_UNWINDING.fields_by_name['transform'].message_type = protos_dot_transform__pb2._RIGIDTRANSFORM3D
_SENSORRECORD.fields_by_name['data_format'].enum_type = _DATAFORMAT
_SENSORRECORD.fields_by_name['pose'].message_type = protos_dot_transform__pb2._WORLDPOSE
_SENSORRECORD.fields_by_name['unwinding'].message_type = _UNWINDING
_LIDARRECORDS.fields_by_name['records'].message_type = _SENSORRECORD
_CAMERARECORDS.fields_by_name['records'].message_type = _SENSORRECORD
_ALIGNEDTRACKRECORDS.fields_by_name['camera_records'].message_type = _CAMERARECORDS
_ALIGNEDTRACKRECORDS.fields_by_name['lidar_records'].message_type = _LIDARRECORDS
DESCRIPTOR.message_types_by_name['Unwinding'] = _UNWINDING
DESCRIPTOR.message_types_by_name['SensorRecord'] = _SENSORRECORD
DESCRIPTOR.message_types_by_name['LidarRecords'] = _LIDARRECORDS
DESCRIPTOR.message_types_by_name['CameraRecords'] = _CAMERARECORDS
DESCRIPTOR.message_types_by_name['AlignedTrackRecords'] = _ALIGNEDTRACKRECORDS
DESCRIPTOR.enum_types_by_name['DataFormat'] = _DATAFORMAT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Unwinding = _reflection.GeneratedProtocolMessageType('Unwinding', (_message.Message,), dict(
  DESCRIPTOR = _UNWINDING,
  __module__ = 'protos.track_data_pb2'
  # @@protoc_insertion_point(class_scope:alignment.data_wrapper.Unwinding)
  ))
_sym_db.RegisterMessage(Unwinding)

SensorRecord = _reflection.GeneratedProtocolMessageType('SensorRecord', (_message.Message,), dict(
  DESCRIPTOR = _SENSORRECORD,
  __module__ = 'protos.track_data_pb2'
  # @@protoc_insertion_point(class_scope:alignment.data_wrapper.SensorRecord)
  ))
_sym_db.RegisterMessage(SensorRecord)

LidarRecords = _reflection.GeneratedProtocolMessageType('LidarRecords', (_message.Message,), dict(
  DESCRIPTOR = _LIDARRECORDS,
  __module__ = 'protos.track_data_pb2'
  # @@protoc_insertion_point(class_scope:alignment.data_wrapper.LidarRecords)
  ))
_sym_db.RegisterMessage(LidarRecords)

CameraRecords = _reflection.GeneratedProtocolMessageType('CameraRecords', (_message.Message,), dict(
  DESCRIPTOR = _CAMERARECORDS,
  __module__ = 'protos.track_data_pb2'
  # @@protoc_insertion_point(class_scope:alignment.data_wrapper.CameraRecords)
  ))
_sym_db.RegisterMessage(CameraRecords)

AlignedTrackRecords = _reflection.GeneratedProtocolMessageType('AlignedTrackRecords', (_message.Message,), dict(
  DESCRIPTOR = _ALIGNEDTRACKRECORDS,
  __module__ = 'protos.track_data_pb2'
  # @@protoc_insertion_point(class_scope:alignment.data_wrapper.AlignedTrackRecords)
  ))
_sym_db.RegisterMessage(AlignedTrackRecords)


# @@protoc_insertion_point(module_scope)
