# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/transform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protos import lat_lng_alt_pb2 as protos_dot_lat__lng__alt__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='protos/transform.proto',
  package='deepmap.api',
  syntax='proto3',
  serialized_options=_b('\n\016ai.deepmap.apiB\016TransformProtoZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protos'),
  serialized_pb=_b('\n\x16protos/transform.proto\x12\x0b\x64\x65\x65pmap.api\x1a\x18protos/lat_lng_alt.proto\"I\n\x0f\x41xisAngleDegree\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\x15\n\rangle_degrees\x18\x04 \x01(\x01\"0\n\rTranslation3d\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"u\n\x10RigidTransform3d\x12\x30\n\naxis_angle\x18\x01 \x01(\x0b\x32\x1c.deepmap.api.AxisAngleDegree\x12/\n\x0btranslation\x18\x02 \x01(\x0b\x32\x1a.deepmap.api.Translation3d\"j\n\tWorldPose\x12+\n\x0blat_lng_alt\x18\x01 \x01(\x0b\x32\x16.deepmap.api.LatLngAlt\x12\x30\n\naxis_angle\x18\x02 \x01(\x0b\x32\x1c.deepmap.api.AxisAngleDegreeB`\n\x0e\x61i.deepmap.apiB\x0eTransformProtoZ>codereview.deepmap.ai/deepmap-go/api/public/deepmap_api/protosb\x06proto3')
  ,
  dependencies=[protos_dot_lat__lng__alt__pb2.DESCRIPTOR,])




_AXISANGLEDEGREE = _descriptor.Descriptor(
  name='AxisAngleDegree',
  full_name='deepmap.api.AxisAngleDegree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='deepmap.api.AxisAngleDegree.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='deepmap.api.AxisAngleDegree.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='deepmap.api.AxisAngleDegree.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='angle_degrees', full_name='deepmap.api.AxisAngleDegree.angle_degrees', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=138,
)


_TRANSLATION3D = _descriptor.Descriptor(
  name='Translation3d',
  full_name='deepmap.api.Translation3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='deepmap.api.Translation3d.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='deepmap.api.Translation3d.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='deepmap.api.Translation3d.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=188,
)


_RIGIDTRANSFORM3D = _descriptor.Descriptor(
  name='RigidTransform3d',
  full_name='deepmap.api.RigidTransform3d',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='axis_angle', full_name='deepmap.api.RigidTransform3d.axis_angle', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translation', full_name='deepmap.api.RigidTransform3d.translation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=307,
)


_WORLDPOSE = _descriptor.Descriptor(
  name='WorldPose',
  full_name='deepmap.api.WorldPose',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lat_lng_alt', full_name='deepmap.api.WorldPose.lat_lng_alt', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='axis_angle', full_name='deepmap.api.WorldPose.axis_angle', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=415,
)

_RIGIDTRANSFORM3D.fields_by_name['axis_angle'].message_type = _AXISANGLEDEGREE
_RIGIDTRANSFORM3D.fields_by_name['translation'].message_type = _TRANSLATION3D
_WORLDPOSE.fields_by_name['lat_lng_alt'].message_type = protos_dot_lat__lng__alt__pb2._LATLNGALT
_WORLDPOSE.fields_by_name['axis_angle'].message_type = _AXISANGLEDEGREE
DESCRIPTOR.message_types_by_name['AxisAngleDegree'] = _AXISANGLEDEGREE
DESCRIPTOR.message_types_by_name['Translation3d'] = _TRANSLATION3D
DESCRIPTOR.message_types_by_name['RigidTransform3d'] = _RIGIDTRANSFORM3D
DESCRIPTOR.message_types_by_name['WorldPose'] = _WORLDPOSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AxisAngleDegree = _reflection.GeneratedProtocolMessageType('AxisAngleDegree', (_message.Message,), dict(
  DESCRIPTOR = _AXISANGLEDEGREE,
  __module__ = 'protos.transform_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.AxisAngleDegree)
  ))
_sym_db.RegisterMessage(AxisAngleDegree)

Translation3d = _reflection.GeneratedProtocolMessageType('Translation3d', (_message.Message,), dict(
  DESCRIPTOR = _TRANSLATION3D,
  __module__ = 'protos.transform_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.Translation3d)
  ))
_sym_db.RegisterMessage(Translation3d)

RigidTransform3d = _reflection.GeneratedProtocolMessageType('RigidTransform3d', (_message.Message,), dict(
  DESCRIPTOR = _RIGIDTRANSFORM3D,
  __module__ = 'protos.transform_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.RigidTransform3d)
  ))
_sym_db.RegisterMessage(RigidTransform3d)

WorldPose = _reflection.GeneratedProtocolMessageType('WorldPose', (_message.Message,), dict(
  DESCRIPTOR = _WORLDPOSE,
  __module__ = 'protos.transform_pb2'
  # @@protoc_insertion_point(class_scope:deepmap.api.WorldPose)
  ))
_sym_db.RegisterMessage(WorldPose)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
