# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

[mypy]
follow_imports = silent
follow_imports_for_stubs = True

# These packages don't provide type-stubs - the ones that provide stubs should be listed in `bazel/typing/BUILD.bazel`
[mypy-PIL.*]
ignore_missing_imports = True

[mypy-scipy.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True

[mypy-cv2.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-open3d.*]
ignore_missing_imports = True
# open3d imports some broken tensorflow libs internally - prevent them from being analyzed
follow_imports = skip

[mypy-point_cloud_utils.*]
ignore_missing_imports = True

[mypy-zarr.*]
ignore_missing_imports = True

[mypy-cbor2.*]
ignore_missing_imports = True

[mypy-numcodecs.*]
ignore_missing_imports = True

[mypy-parameterized.*]
ignore_missing_imports = True

[mypy-debugpy.*]
ignore_missing_imports = True
