# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

from __future__ import annotations

import io
import json
import re

from types import SimpleNamespace
from pathlib import Path
from functools import lru_cache
from typing import NamedTuple, Optional, Union

import numpy as np
import h5py
import PIL.Image as PILImage

import src.dsai_internal.common.transformations as transformations

from . import types, util

VERSION = '3.0.0'
CAMERAS_BASE_GROUP = 'cameras'
LIDARS_BASE_GROUP = 'lidars'
RADARS_BASE_GROUP = 'radars'


class ContainerDataWriter:
    ''' DataWriter implementing format-specific serialization specifications to store V3 / hdf5 data generated by data-converters '''
    def __init__(self, output_dir_path: Path, container_name: str, camera_ids: list[str], lidar_ids: list[str],
                 radar_ids: list[str]):
        ''' 
        Instantiate data writer and initialize the default data groups for a given sequence and sensor IDs
        '''

        self.camera_ids = camera_ids
        self.lidar_ids = lidar_ids
        self.radar_ids = radar_ids

        # Check that sensor-id's are unique across sensor types
        assert len(set(self.camera_ids + self.lidar_ids + self.radar_ids)) == len(self.camera_ids) + len(
            self.lidar_ids) + len(self.radar_ids), 'sensor id\'s are not unique'

        self.output_dir_path = output_dir_path
        self.container_name = container_name

        # Initialize container file
        self.output_dir_path.mkdir(parents=True, exist_ok=True)
        self.container_file = h5py.File(self.output_dir_path / f'{self.container_name}.hdf5', 'w')

        cameras_grp = self.container_file.require_group(CAMERAS_BASE_GROUP)
        for camera_id in self.camera_ids:
            cameras_grp.require_group(camera_id)

        lidars_grp = self.container_file.require_group(LIDARS_BASE_GROUP)
        for lidar_id in self.lidar_ids:
            lidars_grp.require_group(lidar_id)

        radars_grp = self.container_file.require_group(RADARS_BASE_GROUP)
        for radar_id in self.radar_ids:
            radars_grp.require_group(radar_id)

    # Individual 'store*' methods performing data sanity checks and serialize consistent output formats
    def store_meta(self, calibration_type: str, egomotion_type: str) -> None:
        # Store dataset associated meta-data
        self.container_file.attrs.create('version', VERSION)
        self.container_file.attrs.create('egomotion_type', egomotion_type)
        self.container_file.attrs.create('calibration_type', calibration_type)
        self.container_file.attrs.create('camera_ids', self.camera_ids, dtype=h5py.string_dtype())
        self.container_file.attrs.create('lidar_ids', self.lidar_ids, dtype=h5py.string_dtype())
        self.container_file.attrs.create('radar_ids', self.radar_ids, dtype=h5py.string_dtype())

    def store_shard_meta(self, sequence_id: str, shard_id: int, shard_count: int, successful: bool) -> None:
        self.container_file.attrs.create('sequence_id', sequence_id)
        self.container_file.attrs.create('shard_id', shard_id)
        self.container_file.attrs.create('shard_count', shard_count)
        self.container_file.attrs.create('successful', successful)

    def store_poses(self, poses: types.Poses) -> None:
        poses_grp = self.container_file.require_group('poses')
        poses_grp.create_dataset('T_rig_world_base', data=poses.T_rig_world_base)
        poses_grp.create_dataset('T_rig_worlds', data=poses.T_rig_worlds)
        poses_grp.create_dataset('T_rig_world_timestamps_us', data=poses.T_rig_world_timestamps_us)

    def store_labels(self, track_labels: dict[str, types.TrackLabel]) -> None:
        output = {'track_labels': {k: v.to_dict() for (k, v) in track_labels.items()}}

        # TODO: add sanity checks on the final label structure before output

        self.container_file.create_dataset('labels.json', data=json.dumps(output))

    def store_camera_meta(
            self,
            camera_id: str,

            # all frame timestamps
            frame_timestamps_us: np.ndarray,

            # extrinsics
            T_sensor_rig: np.ndarray,

            # intrinsics
            camera_model_parameters: Union[types.FThetaCameraModelParameters, types.PinholeCameraModelParameters],

            # sensor constants
            mask_image: Optional[PILImage.Image]) -> None:
        assert T_sensor_rig.shape == (4, 4)
        assert T_sensor_rig.dtype == np.dtype('float32')
        assert frame_timestamps_us.ndim == 1
        assert frame_timestamps_us.dtype == np.dtype('uint64')

        output = {
            'frame_timestamps_us': frame_timestamps_us.tolist(),
            'T_sensor_rig': T_sensor_rig.tolist(),
            'camera_model_type': camera_model_parameters.type(),
            'camera_model_parameters': camera_model_parameters.to_dict(),
        }

        self.container_file[CAMERAS_BASE_GROUP][camera_id].create_dataset('meta.json', data=json.dumps(output))

        # Output mask if available
        if mask_image:
            with io.BytesIO() as buffer:
                FORMAT = 'png'
                mask_image.save(buffer, format=FORMAT, optimize=True)  # encodes as png
                self.container_file[CAMERAS_BASE_GROUP][camera_id].create_dataset(
                    'mask', data=np.asarray(buffer.getvalue())).attrs.create('format', FORMAT)

    def store_camera_frame(
            self,

            # data indexing
            camera_id: str,
            continous_frame_index: int,

            # image data
            image_file_binary_data: bytes,
            image_file_format: str,

            # poses
            T_rig_worlds: np.ndarray,
            timestamps_us: np.ndarray) -> None:
        # sanity / consistency checks
        assert T_rig_worlds.shape == (2, 4, 4)
        assert T_rig_worlds.dtype == np.dtype('float32')
        assert timestamps_us.shape == (2, )
        assert timestamps_us.dtype == np.dtype('uint64')

        # Initialize frame
        continous_frame_index_string = util.padded_index_string(continous_frame_index)
        frame_group = self.container_file[CAMERAS_BASE_GROUP][camera_id].require_group(continous_frame_index_string)

        # Store image data
        frame_group.create_dataset('image',
                                   data=np.asarray(image_file_binary_data)).attrs.create('format', image_file_format)

        # Output frame meta data
        output = {'T_rig_worlds': T_rig_worlds.tolist(), 'timestamps_us': timestamps_us.tolist()}

        frame_group.create_dataset('meta.json', data=json.dumps(output))

    def store_lidar_meta(
            self,
            lidar_id: str,

            # all frame timestamps
            frame_timestamps_us: np.ndarray,

            # extrinsics
            T_sensor_rig: np.ndarray) -> None:
        assert T_sensor_rig.shape == (4, 4)
        assert T_sensor_rig.dtype == np.dtype('float32')
        assert frame_timestamps_us.shape[1:] == ()
        assert frame_timestamps_us.dtype == np.dtype('uint64')

        output = {'frame_timestamps_us': frame_timestamps_us.tolist(), 'T_sensor_rig': T_sensor_rig.tolist()}

        self.container_file[LIDARS_BASE_GROUP][lidar_id].create_dataset('meta.json', data=json.dumps(output))

    def store_lidar_frame(
            self,

            # data indexing
            lidar_id: str,
            continous_frame_index: int,

            # point-cloud data
            xyz_s: np.ndarray,
            xyz_e: np.ndarray,
            intensity: np.ndarray,
            timestamp_us: np.ndarray,
            dynamic_flag: np.ndarray,

            # label data
            frame_labels: list[types.FrameLabel3],

            # poses
            T_rig_worlds: np.ndarray,
            timestamps_us: np.ndarray) -> None:
        # sanity / consistency checks
        assert xyz_s.shape[1] == 3
        assert xyz_s.dtype == np.dtype('float32')
        assert xyz_e.shape[1] == 3
        assert xyz_e.dtype == np.dtype('float32')
        assert intensity.ndim == 1
        assert intensity.dtype == np.dtype('float32')
        assert timestamp_us.ndim == 1
        assert timestamp_us.dtype == np.dtype('uint64')
        assert dynamic_flag.ndim == 1
        assert dynamic_flag.dtype == np.dtype('int8')
        num_points = xyz_s.shape[0]
        assert all((xyz_s.shape[0] == num_points, xyz_e.shape[0] == num_points, intensity.shape[0] == num_points,
                    timestamp_us.shape[0] == num_points, dynamic_flag.shape[0] == num_points))

        assert T_rig_worlds.shape == (2, 4, 4)
        assert T_rig_worlds.dtype == np.dtype('float32')
        assert timestamps_us.shape == (2, )
        assert timestamps_us.dtype == np.dtype('uint64')

        # Initialize frame
        continous_frame_index_string = util.padded_index_string(continous_frame_index)
        frame_group = self.container_file[LIDARS_BASE_GROUP][lidar_id].require_group(continous_frame_index_string)

        # Store frame data
        COMPRESSION = 'lzf'
        frame_group.create_dataset('xyz_s', data=xyz_s, compression=COMPRESSION)
        frame_group.create_dataset('xyz_e', data=xyz_e, compression=COMPRESSION)
        frame_group.create_dataset('intensity', data=intensity, compression=COMPRESSION)
        frame_group.create_dataset('timestamp_us', data=timestamp_us, compression=COMPRESSION)
        frame_group.create_dataset('dynamic_flag', data=dynamic_flag, compression=COMPRESSION)

        # Output frame meta data
        output = {
            'T_rig_worlds': T_rig_worlds.tolist(),
            'timestamps_us': timestamps_us.tolist(),
            'frame_labels': [frame_label.to_dict() for frame_label in frame_labels],
        }

        frame_group.create_dataset('meta.json', data=json.dumps(output))


class Sensor:
    ''' Provides access to generic data available to all sensor types '''
    class ShardFrame(NamedTuple):
        ''' References a specific frame in a specific shard '''
        shard_index: int
        shard_frame_index: int

    @lru_cache
    def _get_shard_frame(self, continous_frame_index: int) -> ShardFrame:
        ''' For a given continous-frame, determine the corresponding shard-frame '''
        assert continous_frame_index >= 0 and continous_frame_index < self._shard_frame_map[-1], IndexError

        shard_index = int(np.searchsorted(self._shard_frame_map[1:], continous_frame_index, side='right'))
        shard_frame = int(continous_frame_index - self._shard_frame_map[shard_index])

        return self.ShardFrame(shard_index, shard_frame)

    @lru_cache
    def _get_continous_frame(self, shard_frame: ShardFrame) -> int:
        ''' For a given shard-frame, determine the corresponding continous-frame '''
        return self._shard_frame_map[shard_frame.shard_index] + shard_frame.shard_frame_index

    def __init__(self, sensor_id: str, sensor_group: str, shard_files: list[h5py.File]):
        assert len(shard_files), "Require at least a single shard"

        self._sensor_id = sensor_id
        self._sensor_group = sensor_group

        self._shard_files = shard_files

        # Load all shard meta-data
        shard_sensor_metas = [
            json.loads(shard_file[self._sensor_group][self._sensor_id]['meta.json'][()])
            for shard_file in self._shard_files
        ]

        # Construct frame offset map / sensor frame time-range over all shards
        sensor_frame_timestamps_us = [
            np.array(shard_meta['frame_timestamps_us'], dtype=np.uint64) for shard_meta in shard_sensor_metas
        ]

        # Offset map [0, len(s0), len(s0+s1), ... , len(s0+..+sN)]
        self._shard_frame_map = np.hstack([
            0, np.cumsum([len(shard_timestamps_us) for shard_timestamps_us in sensor_frame_timestamps_us])
        ]).astype(np.uint64)

        # Remember single sensor meta of first shard (dropping consumed frame timestamps)
        # [TODO(janickm): add consistency check on static data across all shards?]
        self._sensor_meta = SimpleNamespace(
            **{k: shard_sensor_metas[0][k]
               for k in shard_sensor_metas[0] if k != 'frame_timestamps_us'})

        # Global list of all frame timestamps across all shards
        self._sensor_frame_timestamps_us = np.hstack(sensor_frame_timestamps_us)

        assert len(self._sensor_frame_timestamps_us) == self._shard_frame_map[-1]

    def get_sensor_id(self) -> str:
        ''' Returns the current sensor's ID '''
        return self._sensor_id

    # Extrinsics
    @lru_cache(maxsize=1)
    def get_T_sensor_rig(self) -> np.ndarray:
        ''' Returns constant sensor-to-rig pose '''
        return np.array(self._sensor_meta.T_sensor_rig, dtype=np.float32)

    @lru_cache(maxsize=1)
    def get_T_rig_sensor(self) -> np.ndarray:
        ''' Returns constant rig-to-sensor pose '''
        return transformations.se3_inverse(self.get_T_sensor_rig())

    # Sequence-wide frame data
    def get_frames_count(self) -> int:
        ''' Returns number of frames '''
        return len(self._sensor_frame_timestamps_us)

    def get_frame_index_range(self, start_frame: int = 0, end_frame: int = -1, step_frame: int = 1) -> range:
        ''' Returns a specific range of frame indices following range(start,end,step) conventions '''

        if end_frame == -1:
            end_frame = self.get_frames_count()

        assert start_frame >= 0 and end_frame <= self.get_frames_count(), IndexError

        return range(start_frame, end_frame, step_frame)

    def get_frames_timestamps_us(self) -> np.ndarray:
        ''' Returns all end-of-measurement frame timestamps '''
        return self._sensor_frame_timestamps_us

    # Frame-dependent poses / timestamps
    @lru_cache
    def _get_frame_group(self, continous_frame_index: int) -> h5py.Group:
        ''' Returns the h5 group for a specific frame '''

        shard_frame = self._get_shard_frame(continous_frame_index)

        return self._shard_files[shard_frame.shard_index][self._sensor_group] \
                [self._sensor_id][util.padded_index_string(shard_frame.shard_frame_index)]

    @lru_cache
    def _get_frame_meta(self, continous_frame_index: int) -> dict:
        ''' Returns frame-specific meta data '''

        return json.loads(self._get_frame_group(continous_frame_index)['meta.json'][()])

    @lru_cache
    def get_frame_T_rig_world(self,
                              continous_frame_index: int,
                              frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END) -> np.ndarray:
        ''' Returns start/end rig-to-world pose of specific frame '''

        return np.array(self._get_frame_meta(continous_frame_index)['T_rig_worlds'][frame_timepoint.value])

    @lru_cache
    def get_frame_T_world_rig(self,
                              continous_frame_index: int,
                              frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END) -> np.ndarray:
        ''' Returns start/end world-to-rig pose of specific frame '''
        return transformations.se3_inverse(self.get_frame_T_rig_world(continous_frame_index, frame_timepoint))

    @lru_cache
    def get_frame_T_sensor_world(self,
                                 continous_frame_index: int,
                                 frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END) -> np.ndarray:
        ''' Returns start/end sensor-to-world pose of specific frame '''

        return self.get_frame_T_rig_world(continous_frame_index, frame_timepoint) @ self.get_T_sensor_rig()

    @lru_cache
    def get_frame_T_world_sensor(self, continous_frame_index: int, frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END) -> np.ndarray:
        ''' Returns start/end world-to-sensor pose of specific frame '''
        return transformations.se3_inverse(self.get_frame_T_sensor_world(continous_frame_index, frame_timepoint))

    @lru_cache
    def get_frame_timestamp_us(self,
                               continous_frame_index: int,
                               frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END) -> int:
        ''' Returns timestamp of specific frame timepoints '''

        return self._get_frame_meta(continous_frame_index)['timestamps_us'][frame_timepoint.value]

    @lru_cache
    def get_closest_frame_index(self, timestamp_us: int) -> int:
        ''' Given a timestamp, returns the frame index of the closes frame '''

        return util.closest_index_sorted(self.get_frames_timestamps_us(), timestamp_us)


class CameraSensor(Sensor):
    ''' Provides access to camera-specific sensor-data '''

    # Image Frame Data
    class EncodedImageDataHandle():
        ''' References encoded image data without loading it '''
        def __init__(self, image_dataset: h5py.Dataset):
            self._image_dataset = image_dataset

        @lru_cache(maxsize=1)
        def get_data(self) -> types.EncodedImageData:
            ''' Loads the referenced encoded image data to memory '''
            return types.EncodedImageData(self._image_dataset[()], self._image_dataset.attrs['format'])

    @lru_cache(maxsize=10)
    def get_frame_handle(self, continous_frame_index: int) -> EncodedImageDataHandle:
        ''' Returns the frame's encoded image data '''
        return self.EncodedImageDataHandle(self._get_frame_group(continous_frame_index)['image'])

    @lru_cache(maxsize=10)
    def get_frame_data(self, continous_frame_index: int) -> types.EncodedImageData:
        ''' Returns the frame's encoded image data '''
        return self.get_frame_handle(continous_frame_index).get_data()

    @lru_cache(maxsize=10)
    def get_frame_image(self, continous_frame_index: int) -> PILImage.Image:
        ''' Returns the frame's decoded image data '''
        return self.get_frame_data(continous_frame_index).get_decoded_image()

    @lru_cache(maxsize=10)
    def get_frame_image_array(self, continous_frame_index: int) -> np.ndarray:
        ''' Returns decoded image data as array [W,H,C] '''
        return np.asarray(self.get_frame_image(continous_frame_index))

    # Intrinsics
    @lru_cache(maxsize=1)
    def get_camera_model_parameters(
            self) -> Union[types.FThetaCameraModelParameters, types.PinholeCameraModelParameters]:
        ''' Returns parameters specific to the camera's intrinsic model '''
        if self._sensor_meta.camera_model_type == 'ftheta':
            return types.FThetaCameraModelParameters.from_dict(self._sensor_meta.camera_model_parameters)
        if self._sensor_meta.camera_model_type == 'pinhole':
            return types.PinholeCameraModelParameters.from_dict(self._sensor_meta.camera_model_parameters)
        raise ValueError

    # Camera Mask
    @lru_cache(maxsize=1)
    def get_camera_mask_image(self) -> Optional[PILImage.Image]:
        ''' Returns constant camera mask image, if available '''

        # Take mask from *first* shard
        if not (mask_dataset := self._shard_files[0][self._sensor_group][self._sensor_id].get('mask', default=None)):
            return None

        return PILImage.open(io.BytesIO(mask_dataset[()]), formats=[mask_dataset.attrs['format']])


class PointCloudSensor(Sensor):
    ''' Provides access to sensor's measuring point-clouds '''
    @lru_cache
    def has_frame_data(self, continous_frame_index: int, name: str) -> bool:
        ''' Signals if specifically named frame-data property exists '''

        return name in self._get_frame_group(continous_frame_index)

    @lru_cache(maxsize=10)
    def get_frame_data(self, continous_frame_index: int, name: str) -> np.ndarray:
        ''' Returns frame-data for a specific frame and column-name '''

        return self._get_frame_group(continous_frame_index)[name][()]


class LidarSensor(PointCloudSensor):
    ''' Provides access to lidar-specific sensor-data '''
    @lru_cache
    def get_frame_labels(self, continous_frame_index: int) -> list[types.FrameLabel3]:
        ''' Returns frame-labels for a specific frame '''

        return [
            types.FrameLabel3.from_dict(frame_label)
            for frame_label in self._get_frame_meta(continous_frame_index)['frame_labels']
        ]


class RadarSensor(PointCloudSensor):
    ''' Provides access to radar-specific sensor-data '''
    pass


class ShardDataLoader:
    ''' ShardDataLoader providing convenience methods to load data generated by data-converters '''

    @staticmethod
    def evaluate_shard_file_pattern(pattern: str) -> list[Path]:
        ''' Given a shard-file-pattern returns a list of matching and existing files
        
        Supported patterns (mutually exclusive):
        - integer-ranges: '/some/path/file-[1-3]' will be expanded to [/some/path/file-1, /some/path/file-2, /some/path/file-3]
        
        '''

        pattern_basepath = Path(pattern).parent
        pattern_name = Path(pattern).name

        evaluated_name_patterns = []

        # expand integer ranges like '[1-13]'
        if range_match := re.search(r'\[(\d+)-(\d+)\]', pattern_name):
            low = int(range_match.group(1))
            high = int(range_match.group(2))

            for i in range(low, high + 1):
                evaluated_name_patterns.append(pattern_name.replace(f'[{low}-{high}]', str(i)))
        else:
            evaluated_name_patterns.append(pattern_name)

        matches: set[Path] = set()
        for evaluated_pattern in evaluated_name_patterns:
            for candidate in pattern_basepath.iterdir():
                if candidate.name.startswith(evaluated_pattern):
                    matches.add(candidate)

        return list(matches)


    def __init__(self, shard_files: Union[list[Path], list[str]]):
        assert len(shard_files), "No shard inputs provided"

        # Load shards and check for sequence consistency and continuity of shards
        self._sequence_id = None
        self._camera_ids: list[str] = []
        self._lidar_ids: list[str] = []
        self._radar_ids: list[str] = []
        self._shard_count = None
        self._shard_version = None
        shards_file_map: dict[int, h5py.File] = {}
        for f in shard_files:
            shard_file = h5py.File(f, 'r')

            shard_sequence_id = shard_file.attrs.get('sequence_id')
            shard_camera_ids = shard_file.attrs.get('camera_ids').tolist()
            shard_lidar_ids = shard_file.attrs.get('lidar_ids').tolist()
            shard_radar_ids = shard_file.attrs.get('radar_ids').tolist()
            shard_shard_id = shard_file.attrs.get('shard_id')
            shard_shard_count = shard_file.attrs.get('shard_count')
            shard_shard_version = shard_file.attrs.get('version')

            if not self._sequence_id:
                self._sequence_id = shard_sequence_id
                self._camera_ids = shard_camera_ids
                self._lidar_ids = shard_lidar_ids
                self._radar_ids = shard_radar_ids
                self._shard_count = shard_shard_count
                self._shard_version = shard_shard_version

            assert self._sequence_id == shard_sequence_id, "Can't load shards from different sequences"
            assert self._camera_ids == shard_camera_ids, "Can't load shards with different camera sensors"
            assert self._lidar_ids == shard_lidar_ids, "Can't load shards with different lidar sensors"
            assert self._radar_ids == shard_radar_ids, "Can't load shards with different radar sensors"
            assert self._shard_count == shard_shard_count, "Can't load shards from different subdivisions"
            assert self._shard_version == shard_shard_version, "Can't load shards from different data versions"

            assert shard_shard_id not in shards_file_map, "Shard ID loaded multiple times"
            shards_file_map[shard_shard_id] = shard_file

        # Check version-compatibility
        assert self._shard_version == VERSION, 'loading incompatible version'  # TODO: this check can still be refined

        # Make sure shard IDs are continous
        shard_ids = sorted(list(shards_file_map.keys()))
        assert shard_ids[-1] - shard_ids[0] + 1 == len(shard_ids), f"Non-continous sequence of shards: {shard_ids}"

        # *Linear* sequence of shard files
        self._shard_files = [shards_file_map[shard_id] for shard_id in shard_ids]

        # Initialize all available sensors
        self._sensors: dict[str, Union[CameraSensor, LidarSensor, RadarSensor]] = {}
        self._sensors.update({
            sensor_id: CameraSensor(sensor_id, CAMERAS_BASE_GROUP, self._shard_files)
            for sensor_id in self._camera_ids
        })
        self._sensors.update(
            {sensor_id: LidarSensor(sensor_id, LIDARS_BASE_GROUP, self._shard_files)
             for sensor_id in self._lidar_ids})
        self._sensors.update(
            {sensor_id: RadarSensor(sensor_id, RADARS_BASE_GROUP, self._shard_files)
             for sensor_id in self._radar_ids})

    @lru_cache(maxsize=1)
    def get_poses(self) -> types.Poses:
        ''' Returns all timestamped poses associated with the dataset '''

        # Load common base pose
        # [TODO(janickm): add consistency check on static data across all shards?]
        T_rig_world_base = self._shard_files[0]['poses']['T_rig_world_base']

        # Concat all poses from all shards
        T_rig_worlds = []
        T_rig_world_timestamps_us = []
        for shard_file in self._shard_files:
            T_rig_worlds.append(shard_file['poses']['T_rig_worlds'])
            T_rig_world_timestamps_us.append(shard_file['poses']['T_rig_world_timestamps_us'])

        # [TODO(janickm): add timestamp uniqueness check on data across all shards?]
        return types.Poses(np.array(T_rig_world_base), np.vstack(T_rig_worlds), np.hstack(T_rig_world_timestamps_us))

    def get_sensor(self, sensor_id: str) -> Union[CameraSensor, LidarSensor, RadarSensor]:
        ''' Provides access to a specific sensor given it's sensor-id '''
        return self._sensors[sensor_id]

    def get_camera_ids(self) -> list[str]:
        ''' Returns all camera sensor ids '''
        return self._camera_ids

    def get_lidar_ids(self) -> list[str]:
        ''' Returns all lidar sensor ids '''
        return self._lidar_ids

    def get_radar_ids(self) -> list[str]:
        ''' Returns all radar sensor ids '''
        return self._radar_ids
