# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION
# SPDX-License-Identifier: Apache-2.0

[mypy]
# make command line output easier to read
pretty = True

# do not produce errors for imported code
# (only produce errors for the explicitly listed files)
follow_imports = silent

# follow imports to discover type stubs
follow_imports_for_stubs = True

[mypy-tensorflow.*]
# tensorflow has complex typing that slows down mypy - skip it
follow_imports = skip

[mypy-waymo_open_dataset.*]
# waymo SDK types are not well-typed - skip
follow_imports = skip
