# Copyright (c) 2022 NVIDIA CORPORATION.  All rights reserved.

from __future__ import annotations

import io
import json
import re

import logging
import concurrent.futures

from types import SimpleNamespace
from pathlib import Path
from typing import Iterable, NamedTuple, Optional, Tuple, Union, Dict, List, Union

import numpy as np
import zarr
import numcodecs
import PIL.Image as PILImage

import ncore.impl.common.common as common
import ncore.impl.common.transformations as transformations

from . import types, stores, util

VERSION = "3.0.0"
SENSORS_BASE_GROUP = "sensors"
CAMERAS_BASE_GROUP = "cameras"
LIDARS_BASE_GROUP = "lidars"
RADARS_BASE_GROUP = "radars"

JsonLike = Union[Dict[str, "JsonLike"], List["JsonLike"], str, int, float, bool, None]


class ContainerDataWriter:
    """DataWriter implementing format-specific serialization specifications to store V3 / zarr data generated by data-converters"""

    def __init__(
        self,
        output_dir_path: Path,
        container_name: str,
        camera_ids: List[str],
        lidar_ids: List[str],
        radar_ids: List[str],
        calibration_type: str,
        egomotion_type: str,
        sequence_id: str,
        shard_id: int,
        shard_count: int,
        store_shard_meta: bool,
    ):
        """
        Instantiate data writer and initialize the default data groups for a given sequence and sensor IDs
        """

        self.camera_ids = camera_ids
        self.lidar_ids = lidar_ids
        self.radar_ids = radar_ids

        # Check that sensor-id's are unique across sensor types
        assert len(set(self.camera_ids + self.lidar_ids + self.radar_ids)) == len(self.camera_ids) + len(
            self.lidar_ids
        ) + len(self.radar_ids), "sensor id's are not unique"

        self.output_dir_path = output_dir_path
        self.container_name = container_name
        self.output_container_path = self.output_dir_path / f"{self.container_name}.zarr.itar"

        self.sequence_id = sequence_id
        self.shard_id = shard_id
        self.shard_count = shard_count

        self.store_shard_meta = store_shard_meta

        # Initialize container file (indexed tar file)
        self.output_dir_path.mkdir(parents=True, exist_ok=True)
        self.container_store = stores.IndexedTarStore(self.output_container_path, mode="w")
        self.container_root = zarr.group(store=self.container_store)

        # Store dataset associated meta-data
        self.container_root.attrs.put(
            {
                "version": VERSION,
                "egomotion_type": egomotion_type,
                "calibration_type": calibration_type,
                "camera_ids": self.camera_ids,
                "lidar_ids": self.lidar_ids,
                "radar_ids": self.radar_ids,
                "sequence_id": self.sequence_id,
                "shard_id": self.shard_id,
                "shard_count": self.shard_count,
            }
        )

        # Create sensor groups
        sensors_grp = self.container_root.require_group(SENSORS_BASE_GROUP)
        cameras_grp = sensors_grp.require_group(CAMERAS_BASE_GROUP)
        for camera_id in self.camera_ids:
            cameras_grp.require_group(camera_id)

        lidars_grp = sensors_grp.require_group(LIDARS_BASE_GROUP)
        for lidar_id in self.lidar_ids:
            lidars_grp.require_group(lidar_id)

        radars_grp = sensors_grp.require_group(RADARS_BASE_GROUP)
        for radar_id in self.radar_ids:
            radars_grp.require_group(radar_id)

        # Store initial non-successful shard state
        if self.store_shard_meta:
            self._store_shard_meta(False)

    def _store_shard_meta(self, successful: bool) -> None:
        # Store current shard success state (to distinguish successful / failed conversions without having to load zarr file)
        with open(
            self.output_dir_path
            / f"shard-meta-{self.sequence_id}-{util.padded_index_string(self.shard_id, index_digits=4)}.json",
            "w",
        ) as outfile:
            json.dump({"shard-id": self.shard_id, "shard-count": self.shard_count, "successful": successful}, outfile)

    # To be called after all data was added
    def finalize(self) -> Path:
        """Closes container and returns its path (optionally also writes shard meta data if requested)"""

        # Make sure the shard file is consolidated
        stores.consolidate_compressed_metadata(self.container_store)

        # Finish writing all files
        self.container_store.close()

        # Mark shard as successful
        if self.store_shard_meta:
            self._store_shard_meta(True)

        return self.output_container_path

    # Individual 'store*' methods performing data sanity checks and serialize consistent output formats
    def store_poses(self, poses: types.Poses) -> None:
        poses_grp = self.container_root.require_group("poses")
        poses_grp.create_dataset("T_rig_world_base", data=poses.T_rig_world_base)
        poses_grp.create_dataset("T_rig_worlds", data=poses.T_rig_worlds)
        poses_grp.create_dataset("T_rig_world_timestamps_us", data=poses.T_rig_world_timestamps_us)

    def store_tracks(self, tracks: types.Tracks) -> None:
        # Store track labels
        tracks_grp = self.container_root.require_group("tracks")
        tracks_grp.create_dataset(
            "track_labels",
            dtype=object,
            # Encode as array of (key,value) pairs because of
            # https://github.com/zarr-developers/numcodecs/pull/366
            data=[(k, v.to_dict()) for (k, v) in tracks.track_labels.items()],
            object_codec=numcodecs.JSON(),
        )

    def store_camera_meta(
        self,
        camera_id: str,
        # all frame timestamps
        frame_timestamps_us: np.ndarray,
        # extrinsics
        T_sensor_rig: np.ndarray,
        # intrinsics
        camera_model_parameters: types.ConcreteCameraModelParametersUnion,
        # sensor constants
        mask_image: Optional[PILImage.Image],
        # generic sensor meta-data (needs to be json-serializable)
        generic_meta_data: Dict[str, JsonLike],
    ) -> None:
        assert T_sensor_rig.shape == (4, 4)
        assert T_sensor_rig.dtype == np.dtype("float32")
        assert frame_timestamps_us.ndim == 1
        assert frame_timestamps_us.dtype == np.dtype("uint64")

        # Store meta data
        (camera_grp := self.container_root[SENSORS_BASE_GROUP][CAMERAS_BASE_GROUP][camera_id]).attrs.put(
            {
                "T_sensor_rig": T_sensor_rig.tolist(),
                "camera_model_type": camera_model_parameters.type(),
                "camera_model_parameters": camera_model_parameters.to_dict(),
                "generic_meta_data": generic_meta_data,
            }
        )

        # Store timestamps
        camera_grp.create_dataset("frame_timestamps_us", data=frame_timestamps_us)

        # Store mask if available
        if mask_image:
            with io.BytesIO() as buffer:
                FORMAT = "png"
                mask_image.save(buffer, format=FORMAT, optimize=True)  # encodes as png
                camera_grp.create_dataset("mask", data=np.asarray(buffer.getvalue()), compressor=None).attrs[
                    "format"
                ] = FORMAT

    def store_camera_frame(
        self,
        # data indexing
        camera_id: str,
        continuous_frame_index: int,
        # image data
        image_file_binary_data: bytes,
        image_file_format: str,
        # poses
        T_rig_worlds: np.ndarray,
        timestamps_us: np.ndarray,
        # generic per-frame data (key-value pairs, *not* dimension / dtype validated) and meta-data
        generic_data: Dict[str, np.ndarray],
        generic_meta_data: Dict[str, JsonLike],
    ) -> None:
        # sanity / consistency checks
        assert T_rig_worlds.shape == (2, 4, 4)
        assert T_rig_worlds.dtype == np.dtype("float32")
        assert timestamps_us.shape == (2,)
        assert timestamps_us.dtype == np.dtype("uint64")

        # Initialize frame
        continuous_frame_index_string = util.padded_index_string(continuous_frame_index)
        frame_group = self.container_root[SENSORS_BASE_GROUP][CAMERAS_BASE_GROUP][camera_id].require_group(
            continuous_frame_index_string
        )

        # Store image data
        frame_group.create_dataset("image", data=np.asarray(image_file_binary_data), compressor=None).attrs[
            "format"
        ] = image_file_format

        # Store pose data
        frame_group.create_dataset("T_rig_worlds", data=T_rig_worlds)
        frame_group.create_dataset("timestamps_us", data=timestamps_us)

        # Store additional generic frame data and meta-data (not dimension / dtype checked)
        (frame_generic_data_group := frame_group.require_group("generic_data")).attrs.put(generic_meta_data)
        for name, value in generic_data.items():
            frame_generic_data_group.create_dataset(name, data=value)

    def store_lidar_meta(
        self,
        lidar_id: str,
        # all frame timestamps
        frame_timestamps_us: np.ndarray,
        # extrinsics
        T_sensor_rig: np.ndarray,
        # generic sensor meta-data (has to be json-serializable)
        generic_meta_data: Dict[str, JsonLike],
    ) -> None:
        assert T_sensor_rig.shape == (4, 4)
        assert T_sensor_rig.dtype == np.dtype("float32")
        assert frame_timestamps_us.shape[1:] == ()
        assert frame_timestamps_us.dtype == np.dtype("uint64")

        # Store meta data
        (lidar_grp := self.container_root[SENSORS_BASE_GROUP][LIDARS_BASE_GROUP][lidar_id]).attrs.put(
            {
                "T_sensor_rig": T_sensor_rig.tolist(),
                "generic_meta_data": generic_meta_data,
            }
        )

        # Store timestamps
        lidar_grp.create_dataset("frame_timestamps_us", data=frame_timestamps_us)

    def store_lidar_frame(
        self,
        # data indexing
        lidar_id: str,
        continuous_frame_index: int,
        # point-cloud data
        xyz_s: np.ndarray,
        xyz_e: np.ndarray,
        intensity: np.ndarray,
        timestamp_us: np.ndarray,
        dynamic_flag: np.ndarray,
        # label data
        frame_labels: List[types.FrameLabel3],
        # poses
        T_rig_worlds: np.ndarray,
        timestamps_us: np.ndarray,
        # generic per-frame data (key-value pairs, *not* dimension / dtype validated) and meta-data
        generic_data: Dict[str, np.ndarray],
        generic_meta_data: Dict[str, JsonLike],
    ) -> None:
        # sanity / consistency checks
        assert xyz_e.ndim == 2
        assert xyz_e.shape[1] == 3
        assert xyz_e.dtype == np.dtype("float32")
        num_points = xyz_e.shape[0]

        assert T_rig_worlds.shape == (2, 4, 4)
        assert T_rig_worlds.dtype == np.dtype("float32")
        assert timestamps_us.shape == (2,)
        assert timestamps_us.dtype == np.dtype("uint64")

        # Initialize frame
        continuous_frame_index_string = util.padded_index_string(continuous_frame_index)
        frame_group = self.container_root[SENSORS_BASE_GROUP][LIDARS_BASE_GROUP][lidar_id].require_group(
            continuous_frame_index_string
        )

        # Store frame data
        frame_group.create_dataset("xyz_e", data=xyz_e)

        frame_group.create_dataset(
            "frame_labels",
            dtype=object,
            data=[frame_label.to_dict() for frame_label in frame_labels],
            object_codec=numcodecs.JSON(),
        )

        assert xyz_s.shape == (num_points, 3)
        assert xyz_s.dtype == np.dtype("float32")
        frame_group.create_dataset("xyz_s", data=xyz_s)

        assert intensity.shape == (num_points,)
        assert intensity.dtype == np.dtype("float32")
        frame_group.create_dataset("intensity", data=intensity)

        assert timestamp_us.shape == (num_points,)
        assert timestamp_us.dtype == np.dtype("uint64")
        frame_group.create_dataset("timestamp_us", data=timestamp_us)

        assert dynamic_flag.shape == (num_points,)
        assert dynamic_flag.dtype == np.dtype("int8")
        frame_group.create_dataset("dynamic_flag", data=dynamic_flag)

        # Store pose data
        frame_group.create_dataset("T_rig_worlds", data=T_rig_worlds)
        frame_group.create_dataset("timestamps_us", data=timestamps_us)

        # Store additional generic frame data and meta-data (not dimension / dtype checked)
        (frame_generic_data_group := frame_group.require_group("generic_data")).attrs.put(generic_meta_data)
        for name, value in generic_data.items():
            frame_generic_data_group.create_dataset(name, data=value)

    def store_radar_meta(
        self,
        radar_id: str,
        # all frame timestamps
        frame_timestamps_us: np.ndarray,
        # extrinsics
        T_sensor_rig: np.ndarray,
        # generic sensor meta-data (has to be json-serializable)
        generic_meta_data: Dict[str, JsonLike],
    ) -> None:
        assert T_sensor_rig.shape == (4, 4)
        assert T_sensor_rig.dtype == np.dtype("float32")
        assert frame_timestamps_us.shape[1:] == ()
        assert frame_timestamps_us.dtype == np.dtype("uint64")

        # Store meta data
        (radar_grp := self.container_root[SENSORS_BASE_GROUP][RADARS_BASE_GROUP][radar_id]).attrs.put(
            {
                "T_sensor_rig": T_sensor_rig.tolist(),
                "generic_meta_data": generic_meta_data,
            }
        )

        # Store timestamps
        radar_grp.create_dataset("frame_timestamps_us", data=frame_timestamps_us)

    def store_radar_frame(
        self,
        # data indexing
        radar_id: str,
        continuous_frame_index: int,
        # point-cloud data
        xyz_s: np.ndarray,
        xyz_e: np.ndarray,
        # poses
        T_rig_worlds: np.ndarray,
        timestamps_us: np.ndarray,
        # generic per-frame data (key-value pairs, *not* dimension / dtype validated) and meta-data
        generic_data: Dict[str, np.ndarray],
        generic_meta_data: Dict[str, JsonLike],
    ) -> None:
        # sanity / consistency checks

        assert xyz_e.ndim == 2
        assert xyz_e.shape[1] == 3
        assert xyz_e.dtype == np.dtype("float32")
        num_points = xyz_e.shape[0]

        assert T_rig_worlds.shape == (2, 4, 4)
        assert T_rig_worlds.dtype == np.dtype("float32")
        assert timestamps_us.shape == (2,)
        assert timestamps_us.dtype == np.dtype("uint64")

        # Initialize frame
        continuous_frame_index_string = util.padded_index_string(continuous_frame_index)
        frame_group = self.container_root[SENSORS_BASE_GROUP][RADARS_BASE_GROUP][radar_id].require_group(
            continuous_frame_index_string
        )

        # Store frame data
        frame_group.create_dataset("xyz_e", data=xyz_e)

        assert xyz_s.shape == (num_points, 3)
        assert xyz_s.dtype == np.dtype("float32")
        frame_group.create_dataset("xyz_s", data=xyz_s)

        # Store pose data
        frame_group.create_dataset("T_rig_worlds", data=T_rig_worlds)
        frame_group.create_dataset("timestamps_us", data=timestamps_us)

        # Store additional generic frame data and meta-data (not dimension / dtype checked)
        (frame_generic_data_group := frame_group.require_group("generic_data")).attrs.put(generic_meta_data)
        for name, value in generic_data.items():
            frame_generic_data_group.create_dataset(name, data=value)


class Sensor:
    """Provides access to generic data available to all sensor types"""

    class _ShardFrame(NamedTuple):
        """References a specific frame in a specific shard"""

        shard_index: int
        shard_frame_index: int

    def _get_shard_frame(self, continuous_frame_index: int) -> _ShardFrame:
        """For a given continuous-frame, determine the corresponding shard-frame"""
        assert continuous_frame_index >= 0 and continuous_frame_index < self._shard_frame_map[-1], IndexError

        shard_index = int(np.searchsorted(self._shard_frame_map[1:], continuous_frame_index, side="right"))
        shard_frame = int(continuous_frame_index - self._shard_frame_map[shard_index])

        return self._ShardFrame(shard_index, shard_frame)

    def _get_continuous_frame(self, shard_frame: _ShardFrame) -> int:
        """For a given shard-frame, determine the corresponding continuous-frame"""
        return self._shard_frame_map[shard_frame.shard_index] + shard_frame.shard_frame_index

    def __init__(self, sensor_id: str, sensor_group: str, shard_roots: List[zarr.Group]):
        assert len(shard_roots), "Require at least a single shard"

        self._sensor_id = sensor_id
        self._sensor_group = sensor_group

        self._shard_roots = shard_roots

        # Load cross-shard sensor information concurrently to hide latencies
        with concurrent.futures.ThreadPoolExecutor() as executor:

            def thread_load_shard(shard_root):
                """Thread-executed shard data loading"""

                # Look up shard sensor group *once* (preventing expensive zarr hierarchy traversal later on)
                shard_sensor_group = shard_root[SENSORS_BASE_GROUP][self._sensor_group][self._sensor_id]

                # Load shard-associated sensor meta-data
                shard_sensor_meta = shard_sensor_group.attrs.asdict()

                # Load shard-associated sensor timestamps
                shard_sensor_frame_timestamps_us = shard_sensor_group["frame_timestamps_us"][()]

                return shard_sensor_group, shard_sensor_meta, shard_sensor_frame_timestamps_us

            # Load in multi-threaded fashion, making sure order is preserved
            shard_sensor_groups, shard_sensor_metas, shards_sensor_frame_timestamps_us = zip(
                *executor.map(thread_load_shard, self._shard_roots)
            )

        self._shard_sensor_group = shard_sensor_groups

        # Construct frame offset map / sensor frame time-range over all shards as
        # offset map [0, len(s0), len(s0+s1), ... , len(s0+..+sN)]
        self._shard_frame_map = np.hstack(
            [
                0,
                np.cumsum(
                    [
                        len(shard_sensor_frame_timestamps_us)
                        for shard_sensor_frame_timestamps_us in shards_sensor_frame_timestamps_us
                    ]
                ),
            ]
        ).astype(np.uint64)

        # Remember single sensor meta of first shard
        # [TODO(janickm): add consistency check on static data across all shards?]
        self._sensor_meta = SimpleNamespace(**shard_sensor_metas[0])

        # Global list of all frame timestamps per shard
        self._shards_sensor_frame_timestamps_us = shards_sensor_frame_timestamps_us

        assert (
            sum(
                len(shard_sensor_frame_timestamps_us)
                for shard_sensor_frame_timestamps_us in self._shards_sensor_frame_timestamps_us
            )
            == self._shard_frame_map[-1]
        )

    def get_sensor_id(self) -> str:
        """Returns the current sensor's ID"""
        return self._sensor_id

    # Extrinsics
    def get_T_sensor_rig(self) -> np.ndarray:
        """Returns constant sensor-to-rig pose"""
        return np.array(self._sensor_meta.T_sensor_rig, dtype=np.float32)

    def get_T_rig_sensor(self) -> np.ndarray:
        """Returns constant rig-to-sensor pose"""
        return transformations.se3_inverse(self.get_T_sensor_rig())

    # Generic sensor meta-data
    def get_generic_meta_data(self) -> Dict[str, JsonLike]:
        """Returns the generic sensor meta-data"""

        if "generic_meta_data" not in self._sensor_meta.__dict__:
            # Backwards-compatibility for data that didn't store generic_meta_data
            return {}

        return self._sensor_meta.generic_meta_data

    # Sequence-wide or shard-wide frame data
    def get_frames_count(self, start_shard_idx: Optional[int] = None, stop_shard_idx: Optional[int] = None) -> int:
        """Returns number of frames for full session (default) or a range of shards [start,stop)"""
        return sum(
            len(shard_sensor_frame_timestamps_us)
            for shard_sensor_frame_timestamps_us in self._shards_sensor_frame_timestamps_us[
                start_shard_idx:stop_shard_idx
            ]
        )

    def get_frame_index_range(
        self,
        start_frame_index: Optional[int] = None,
        stop_frame_index: Optional[int] = None,
        step_frame_index: Optional[int] = None,
    ) -> range:
        """Returns a (potentially empty) range of frame indices following start:stop:step slice conventions,
        defaulting to full frame index range for absent range bound specifiers
        """

        return range(*slice(start_frame_index, stop_frame_index, step_frame_index).indices(self.get_frames_count()))

    def get_frames_timestamps_us(
        self, start_shard_idx: Optional[int] = None, stop_shard_idx: Optional[int] = None
    ) -> np.ndarray:
        """Returns all end-of-measurement frame timestamps full session (default) or a range of shards [start,stop)"""
        return np.hstack(self._shards_sensor_frame_timestamps_us[start_shard_idx:stop_shard_idx])

    # Frame-dependent poses / timestamps / data
    def _get_frame_group(self, continuous_frame_index: int) -> zarr.Group:
        """Returns the zarr group for a specific frame"""

        shard_frame = self._get_shard_frame(continuous_frame_index)

        return self._shard_sensor_group[shard_frame.shard_index][
            util.padded_index_string(shard_frame.shard_frame_index)
        ]

    def get_frame_T_rig_world(
        self, continuous_frame_index: int, frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END
    ) -> np.ndarray:
        """Returns start/end rig-to-world pose of specific frame"""

        return self._get_frame_group(continuous_frame_index)["T_rig_worlds"][frame_timepoint.value]

    def get_frame_T_world_rig(
        self, continuous_frame_index: int, frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END
    ) -> np.ndarray:
        """Returns start/end world-to-rig pose of specific frame"""
        return transformations.se3_inverse(self.get_frame_T_rig_world(continuous_frame_index, frame_timepoint))

    def get_frame_T_sensor_world(
        self, continuous_frame_index: int, frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END
    ) -> np.ndarray:
        """Returns start/end sensor-to-world pose of specific frame"""

        return self.get_frame_T_rig_world(continuous_frame_index, frame_timepoint) @ self.get_T_sensor_rig()

    def get_frame_T_world_sensor(
        self, continuous_frame_index: int, frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END
    ) -> np.ndarray:
        """Returns start/end world-to-sensor pose of specific frame"""
        return transformations.se3_inverse(self.get_frame_T_sensor_world(continuous_frame_index, frame_timepoint))

    def get_frame_timestamp_us(
        self, continuous_frame_index: int, frame_timepoint: types.FrameTimepoint = types.FrameTimepoint.END
    ) -> int:
        """Returns timestamp of specific frame timepoints"""

        return self._get_frame_group(continuous_frame_index)["timestamps_us"][frame_timepoint.value]

    def get_closest_frame_index(self, timestamp_us: int) -> int:
        """Given a timestamp, returns the frame index of the closes frame"""

        return util.closest_index_sorted(self.get_frames_timestamps_us(), timestamp_us)

    # Generic per-frame data
    def get_frame_generic_data_names(self, continuous_frame_index: int) -> List[str]:
        """List of all generic frame-data names"""

        if "generic_data" not in (frame_group := self._get_frame_group(continuous_frame_index)):
            # Backwards-compatibility for data that didn't store generic_data
            return []

        return list(frame_group["generic_data"].keys())

    def has_frame_generic_data(self, continuous_frame_index: int, name: str) -> bool:
        """Signals if named generic frame-data exists"""

        return name in self.get_frame_generic_data_names(continuous_frame_index)

    def get_frame_generic_data(self, continuous_frame_index: int, name: str) -> np.ndarray:
        """Returns generic frame-data for a specific frame and name"""

        if not self.has_frame_generic_data(continuous_frame_index, name):
            raise ValueError(
                f"Sensor {self._sensor_id} is missing generic meta-data '{name}' for frame {continuous_frame_index}"
            )

        return self._get_frame_group(continuous_frame_index)["generic_data"][name][()]

    def get_frame_generic_meta_data(self, continuous_frame_index) -> Dict[str, JsonLike]:
        """Returns generic frame meta-data for a specific frame"""

        if "generic_data" not in (frame_group := self._get_frame_group(continuous_frame_index)):
            # Backwards-compatibility for data that didn't store generic_data
            return {}

        return frame_group["generic_data"].attrs.asdict()


class CameraSensor(Sensor):
    """Provides access to camera-specific sensor-data"""

    # Image Frame Data
    class EncodedImageDataHandle:
        """References encoded image data without loading it"""

        def __init__(self, image_dataset: zarr.Array):
            self._image_dataset = image_dataset

        def get_data(self) -> types.EncodedImageData:
            """Loads the referenced encoded image data to memory"""
            return types.EncodedImageData(self._image_dataset[()], self._image_dataset.attrs["format"])

    def get_frame_handle(self, continuous_frame_index: int) -> EncodedImageDataHandle:
        """Returns the frame's encoded image data"""
        return self.EncodedImageDataHandle(self._get_frame_group(continuous_frame_index)["image"])

    def get_frame_data(self, continuous_frame_index: int) -> types.EncodedImageData:
        """Returns the frame's encoded image data"""
        return self.get_frame_handle(continuous_frame_index).get_data()

    def get_frame_image(self, continuous_frame_index: int) -> PILImage.Image:
        """Returns the frame's decoded image data"""
        return self.get_frame_data(continuous_frame_index).get_decoded_image()

    def get_frame_image_array(self, continuous_frame_index: int) -> np.ndarray:
        """Returns decoded image data as array [W,H,C]"""
        return np.asarray(self.get_frame_image(continuous_frame_index))

    # Intrinsics
    def get_camera_model_parameters(self) -> types.ConcreteCameraModelParametersUnion:
        """Returns parameters specific to the camera's intrinsic model"""
        if self._sensor_meta.camera_model_type == "ftheta":
            return types.FThetaCameraModelParameters.from_dict(self._sensor_meta.camera_model_parameters)
        if self._sensor_meta.camera_model_type in [
            "opencv-pinhole",
            # keep 'pinhole' for backwards-compatibility with existing data
            "pinhole",
        ]:
            return types.OpenCVPinholeCameraModelParameters.from_dict(self._sensor_meta.camera_model_parameters)
        if self._sensor_meta.camera_model_type == "opencv-fisheye":
            return types.OpenCVFisheyeCameraModelParameters.from_dict(self._sensor_meta.camera_model_parameters)
        raise ValueError

    # Camera Mask
    def get_camera_mask_image(self) -> Optional[PILImage.Image]:
        """Returns constant camera mask image, if available"""

        # Take mask from *first* shard
        if (mask_dataset := self._shard_sensor_group[0].get("mask", default=None)) is None:
            return None

        return PILImage.open(io.BytesIO(mask_dataset[()]), formats=[mask_dataset.attrs["format"]])


class PointCloudSensor(Sensor):
    """Provides access to sensor's measuring point-clouds"""

    def has_frame_data(self, continuous_frame_index: int, name: str) -> bool:
        """Signals if specifically named frame-data property exists"""

        return name in self._get_frame_group(continuous_frame_index)

    def get_frame_data(self, continuous_frame_index: int, name: str) -> np.ndarray:
        """Returns frame-data for a specific frame and name"""

        return self._get_frame_group(continuous_frame_index)[name][()]


class LidarSensor(PointCloudSensor):
    """Provides access to lidar-specific sensor-data"""

    def get_frame_labels(self, continuous_frame_index: int) -> List[types.FrameLabel3]:
        """Returns frame-labels for a specific frame"""

        return [
            types.FrameLabel3.from_dict(frame_label, infer_missing=True)
            for frame_label in self._get_frame_group(continuous_frame_index)["frame_labels"]
        ]


class RadarSensor(PointCloudSensor):
    """Provides access to radar-specific sensor-data"""

    pass


class ShardDataLoader:
    """ShardDataLoader providing convenience methods to load data generated by data-converters"""

    @staticmethod
    def evaluate_shard_file_pattern(pattern: str, skip_suffixes: Iterable[str] = ()) -> List[str]:
        """Given a shard-file-pattern returns a list of matching and existing files

        Supported patterns (mutually exclusive):
        - integer-ranges: '/some/path/file-[1-3]' will be expanded to [/some/path/file-1, /some/path/file-2, /some/path/file-3]

        """

        pattern_basepath = Path(pattern).parent
        pattern_name = Path(pattern).name

        evaluated_name_patterns = []

        # expand integer ranges like '[1-13]'
        if range_match := re.search(r"\[(\d+)-(\d+)\]", pattern_name):
            low = int(range_match.group(1))
            high = int(range_match.group(2))

            for i in range(low, high + 1):
                evaluated_name_patterns.append(pattern_name.replace(f"[{low}-{high}]", str(i) + "-"))
        else:
            evaluated_name_patterns.append(pattern_name)

        matches: set[Path] = set()
        for evaluated_pattern in evaluated_name_patterns:
            for candidate in pattern_basepath.iterdir():
                if candidate.name.startswith(evaluated_pattern):
                    skip = False
                    for skip_suffix in skip_suffixes:
                        if str(candidate).endswith(skip_suffix):
                            skip = True
                            break
                    if not skip:
                        matches.add(candidate)

        return [str(match) for match in list(matches)]

    def __init__(self, shard_paths: List[str], open_consolidated: bool = True):
        """Initialize a ShardDataLoader for a virtual sequence represented by a list of shard files.

        Args:
            shard_files: Paths / URLs to shard files to load, which need to represent a *continuous* sequence
            open_consolidated: If 'True', pre-load per-shard meta-data when opening the shards.
                               This is advisable if shard data is accessed from *non-local*
                               storage to prevent latencies introduced when accessing the data.
                               If the shard data is available on fast *local* storage, disabling
                               this option can speed up initial load times.
        """

        assert len(shard_paths), "No shard inputs provided"

        # Load shards concurrently (to hide latency) and check for sequence consistency and continuity of shards
        shards_map: Dict[
            int, Tuple[str, zarr.Group, stores.IndexedTarStore]
        ] = {}  # use str as the generic path / URL type

        with concurrent.futures.ThreadPoolExecutor() as executor:

            def thread_load_shard(shard_path):
                """Thread-executed shard opening"""

                # Make sure paths are absolute at this point - in the future we might have fully-resolved URLs instead here, too
                shard_path = Path(shard_path).absolute()

                logging.info(f"ShardDataLoader: Loading shard {shard_path}")

                timer = common.SimpleTimer()
                shard_store = stores.IndexedTarStore(shard_path)
                shard_root = (
                    stores.open_compressed_consolidated(store=shard_store, mode="r")
                    if open_consolidated
                    else zarr.open(store=shard_store, mode="r")
                )

                logging.debug(f"ShardDataLoader: {shard_path} time_load={timer.elapsed_sec()}sec")

                return str(shard_path), shard_root, shard_store

            for future in concurrent.futures.as_completed(
                [executor.submit(thread_load_shard, shard_path) for shard_path in shard_paths]
            ):
                # Note: thread completion order is not relevant here
                shard_path, shard_root, shard_store = future.result()

                shard_sequence_id = shard_root.attrs.get("sequence_id")
                shard_camera_ids = set(shard_root.attrs.get("camera_ids"))
                shard_lidar_ids = set(shard_root.attrs.get("lidar_ids"))
                shard_radar_ids = set(shard_root.attrs.get("radar_ids"))
                shard_shard_id = shard_root.attrs.get("shard_id")
                shard_shard_count = shard_root.attrs.get("shard_count")
                shard_version = shard_root.attrs.get("version")
                shard_calibration_type = shard_root.attrs.get("calibration_type")
                shard_egomotion_type = shard_root.attrs.get("egomotion_type")

                if not shards_map:
                    self._sequence_id: str = shard_sequence_id
                    self._camera_ids: set[str] = shard_camera_ids
                    self._lidar_ids: set[str] = shard_lidar_ids
                    self._radar_ids: set[str] = shard_radar_ids
                    self._shard_count: int = shard_shard_count
                    self._shard_version: str = shard_version
                    self._calibration_type: str = shard_calibration_type
                    self._egomotion_type: str = shard_egomotion_type

                if not self._sequence_id == shard_sequence_id:
                    raise ValueError("Can't load shards from different sequences")
                if not self._camera_ids == shard_camera_ids:
                    raise ValueError("Can't load shards with different camera sensors")
                if not self._lidar_ids == shard_lidar_ids:
                    raise ValueError("Can't load shards with different lidar sensors")
                if not self._radar_ids == shard_radar_ids:
                    raise ValueError("Can't load shards with different radar sensors")
                if not self._shard_count == shard_shard_count:
                    raise ValueError("Can't load shards from different subdivisions")
                if not self._shard_version == shard_version:
                    raise ValueError("Can't load shards from different data versions")
                if not self._calibration_type == shard_calibration_type:
                    raise ValueError("Can't load shards with different calibration types")
                if not self._egomotion_type == shard_egomotion_type:
                    raise ValueError("Can't load shards with different egomotion types")

                if shard_shard_id in shards_map:
                    raise ValueError("Shard ID loaded multiple times")

                shards_map[shard_shard_id] = shard_path, shard_root, shard_store

        # Check version-compatibility
        if self._shard_version != VERSION:
            raise ValueError(
                f"Loading incompatible version {self._shard_version}, supporting {VERSION} only"
            )  # TODO: this check can still be refined

        # Make sure shard IDs are continuous
        self._shard_ids = sorted(list(shards_map.keys()))
        if self._shard_ids[-1] - self._shard_ids[0] + 1 != len(self._shard_ids):
            raise ValueError(f"Loading non-continuous sequence of shards: {self._shard_ids}")

        # *Linear* sequences of shards
        self._shard_paths = [shards_map[shard_id][0] for shard_id in self._shard_ids]
        self._shard_roots = [shards_map[shard_id][1] for shard_id in self._shard_ids]
        self._shard_stores = [shards_map[shard_id][2] for shard_id in self._shard_ids]

    def reload_store_resources(self) -> None:
        """Trigger a reload of each shard store - useful to re-initialize file objects in multi-process settings"""
        for shard_store in self._shard_stores:
            shard_store.reload_resources()

    def get_poses(self, start_shard_idx: Optional[int] = None, stop_shard_idx: Optional[int] = None) -> types.Poses:
        """Returns all timestamped poses associated with the session (default) or a range of shards [start,stop)"""

        # Load common base pose
        # [TODO(janickm): add consistency check on static data across all shards?]
        T_rig_world_base = self._shard_roots[0]["poses"]["T_rig_world_base"]

        # Concat all poses from all shards, making sure they are uniquely timestamped and sorted
        T_rig_worlds = []
        T_rig_world_timestamps_us = []
        for shard_root in self._shard_roots[start_shard_idx:stop_shard_idx]:
            shard_T_rig_worlds = shard_root["poses"]["T_rig_worlds"][()]
            shard_T_rig_world_timestamps_us = shard_root["poses"]["T_rig_world_timestamps_us"][()]

            if len(shard_T_rig_worlds) != len(shard_T_rig_world_timestamps_us):
                raise ValueError(f"Inconsistent pose number / timestamp number for shard: {shard_root}")

            if not np.all(shard_T_rig_world_timestamps_us[:-1] < shard_T_rig_world_timestamps_us[1:]):
                raise ValueError(f"Pose timestamps not strictly monotonically increasing for shard: {shard_root}")

            T_rig_worlds.append(shard_T_rig_worlds)
            T_rig_world_timestamps_us.append(shard_T_rig_world_timestamps_us)

        # Shards are allowed to have *single* overlapping poses across their boundary - remove these via unique search -
        # and make sure that pose timestamps are ordered in strictly monotonically increasing order afterwards
        T_rig_world_timestamps_us, unique_idxs, unique_counts = np.unique(
            np.hstack(T_rig_world_timestamps_us), return_index=True, return_counts=True
        )

        # Verify that overlapping poses showed up duplicated only once after concatenation
        if not np.all(unique_counts <= 2):
            raise ValueError(f"Concatenated pose timestamps contain more than a single overlapping common pose")

        # Make sure that concatenated timestamps were actually already sorted before unification
        if not np.all(unique_idxs[:-1] < unique_idxs[1:]):
            raise ValueError(f"Concatenated pose timestamps not strictly monotonically increasing")

        return types.Poses(
            np.array(T_rig_world_base), np.vstack(T_rig_worlds)[unique_idxs], np.hstack(T_rig_world_timestamps_us)
        )

    def get_sequence_id(self, with_shard_range: bool = False) -> str:
        """Provides access to a unique identifier of the loaded shard data, optionally including the linear range of shards

        Examples:
        - with_shard_range == False: c9b05cf4-afb9-11ec-b3c2-00044bf65fcb
        - with_shard_range == True:  c9b05cf4-afb9-11ec-b3c2-00044bf65fcb_2_3_4 [assuming shards 2,3,4 were loaded]
        """
        if with_shard_range:
            return f"{self._sequence_id}_{'_'.join([str(shard_id) for shard_id in self._shard_ids])}"
        return self._sequence_id

    def get_calibration_type(self) -> str:
        """Provides access to a calibration type identifier of the loaded shard data"""
        return self._calibration_type

    def get_egomotion_type(self) -> str:
        """Provides access to a egomotion type identifier of the loaded shard data"""
        return self._egomotion_type

    def get_shard_paths(self) -> List[str]:
        """Returns paths to loaded shards (ordered by linear shard ID)"""
        return self._shard_paths

    def get_shard_ids(self) -> List[int]:
        """Returns linearly ordered list of loaded shard IDs"""
        return self._shard_ids

    def get_sensor(self, sensor_id: str) -> Union[CameraSensor, LidarSensor, RadarSensor]:
        """Provides access to a specific sensor given its sensor-id"""
        if sensor_id in self._camera_ids:
            return self.get_camera_sensor(sensor_id)
        if sensor_id in self._lidar_ids:
            return self.get_lidar_sensor(sensor_id)
        if sensor_id in self._radar_ids:
            return self.get_radar_sensor(sensor_id)
        raise ValueError(f"Unknown sensor {sensor_id}")

    def get_sensor_ids(self) -> List[str]:
        """Returns all sensor ids"""
        return self.get_camera_ids() + self.get_lidar_ids() + self.get_radar_ids()

    def get_camera_sensor(self, camera_id) -> CameraSensor:
        """Provides access to a specific camera sensor given its sensor-id"""
        return CameraSensor(camera_id, CAMERAS_BASE_GROUP, self._shard_roots)

    def get_camera_ids(self) -> List[str]:
        """Returns all camera sensor ids"""
        return list(self._camera_ids)

    def get_lidar_sensor(self, lidar_id) -> LidarSensor:
        """Provides access to a specific lidar sensor given its sensor-id"""
        return LidarSensor(lidar_id, LIDARS_BASE_GROUP, self._shard_roots)

    def get_lidar_ids(self) -> List[str]:
        """Returns all lidar sensor ids"""
        return list(self._lidar_ids)

    def get_radar_sensor(self, radar_id) -> RadarSensor:
        """Provides access to a specific radar sensor given its sensor-id"""
        return RadarSensor(radar_id, RADARS_BASE_GROUP, self._shard_roots)

    def get_radar_ids(self) -> List[str]:
        """Returns all radar sensor ids"""
        return list(self._radar_ids)

    def get_tracks(self) -> types.Tracks:
        """Returns all object tracks"""

        root_shard = self._shard_roots[0]  # can use first root shard as track labels are the same per shard

        # Backwards-compatibility: track-labels used to be stored in top-level
        # 'labels' group / 'track_labels' dataset
        tracks_group = root_shard["labels"] if "labels" in root_shard else root_shard["tracks"]

        return types.Tracks(
            track_labels={
                track_label[0]: types.TrackLabel.from_dict(track_label[1], infer_missing=True)
                for track_label in tracks_group["track_labels"]
            }
        )
